
/* =========================================================
   Cmdlets : CIM / WMI, journaux, système
   ========================================================= */
const WINRM_MSG=h=>`La connexion au serveur distant ${h} a échoué avec le message d’erreur suivant : Le client WinRM ne peut pas effectuer l’opération dans le temps imparti. Vérifiez si le nom de l’ordinateur est valide, s’il est accessible sur le réseau et si une exception de pare-feu pour le service WinRM est activée et autorise l’accès à partir de cet ordinateur.`;
const WINRM_HINT='(Sur ce domaine, WinRM est désactivé sur les postes. Alternatives sans WinRM : New-CimSession avec -SessionOption (New-CimSessionOption -Protocol Dcom), Get-Service -ComputerName, sc.exe \\\\PC, \\\\PC\\C$, PsExec, Restart-Computer -ComputerName.)';
function cimClass(cls,hostN){
  const c=lc(cls).replace(/^cim_/,'win32_');const hw=hostHw(hostN||'PC-IT-01');const pc=(hostN||'PC-IT-01').toUpperCase();
  const T=n=>(hostN&&!findHost(hostN).self?'Microsoft.Management.Infrastructure.CimInstance#root/cimv2/':'Microsoft.Management.Infrastructure.CimInstance#root/cimv2/')+n;
  const O=(n,p)=>mk(T(n),Object.assign(p,{PSComputerName:hostN&&!findHost(hostN).self?pc:null}),{__s:n});
  switch(c){
    case'win32_operatingsystem':return[O('Win32_OperatingSystem',{SystemDirectory:'C:\\Windows\\system32',Organization:'Contoso Hôtels',BuildNumber:hw.build,RegisteredUser:'Contoso Hôtels',SerialNumber:'00330-80000-00000-AA412',Version:hw.ver,Caption:hw.os,CSName:pc,OSArchitecture:'64 bits',InstallDate:hw.install,LastBootUpTime:hw.boot,LocalDateTime:new Date(),FreePhysicalMemory:Math.round(hw.ram*1048576*0.46),TotalVisibleMemorySize:hw.ram*1048576-284672,NumberOfUsers:hw.user?1:0,MUILanguages:['fr-FR'],ProductType:/^SRV/.test(pc)?3:1})];
    case'win32_computersystem':return[O('Win32_ComputerSystem',{Name:pc,PrimaryOwnerName:'Contoso Hôtels',Domain:'contoso.local',TotalPhysicalMemory:hw.ram*1073741824-291504128,Model:hw.model,Manufacturer:hw.man,UserName:hw.user,DomainRole:/^SRV-AD/.test(pc)?5:/^SRV/.test(pc)?3:1,PartOfDomain:true,NumberOfProcessors:1,NumberOfLogicalProcessors:hw.lp,SystemType:'x64-based PC'})];
    case'win32_bios':return[O('Win32_BIOS',{SMBIOSBIOSVersion:'1.21.0',Manufacturer:hw.man,Name:'1.21.0',SerialNumber:hw.serial,Version:'DELL   - 1072009',ReleaseDate:new Date(2026,4,14)})];
    case'win32_computersystemproduct':return[O('Win32_ComputerSystemProduct',{IdentifyingNumber:hw.serial,Name:hw.model,Vendor:hw.man,Version:'',Caption:'Produit système informatique',UUID:guid(pc).toUpperCase()})];
    case'win32_processor':return[O('Win32_Processor',{DeviceID:'CPU0',Name:hw.cpu,Caption:'Intel64 Family 6 Model 191 Stepping 2',MaxClockSpeed:2500,SocketDesignation:'LGA1700',Manufacturer:'GenuineIntel',NumberOfCores:hw.cores,NumberOfLogicalProcessors:hw.lp,LoadPercentage:12})];
    case'win32_logicaldisk':{const isMe=!hostN||findHost(hostN).self;const C=isMe?{size:511,free:FREE.C/1073741824}:hw.c;
      const disks=[O('Win32_LogicalDisk',{DeviceID:'C:',DriveType:3,ProviderName:null,VolumeName:'OS',Size:Math.round(C.size*1073741824),FreeSpace:Math.round(C.free*1073741824),FileSystem:'NTFS',VolumeSerialNumber:'7A3C91F2'})];
      if(isMe){disks.push(O('Win32_LogicalDisk',{DeviceID:'D:',DriveType:3,ProviderName:null,VolumeName:'DATA',Size:1000202039296,FreeSpace:FREE.D,FileSystem:'NTFS',VolumeSerialNumber:'B2E10C44'}));
        Object.keys(st.mapped).forEach(k=>disks.push(O('Win32_LogicalDisk',{DeviceID:k+':',DriveType:4,ProviderName:st.mapped[k].unc,VolumeName:'Data',Size:3298534883328,FreeSpace:1209462790553,FileSystem:'NTFS',VolumeSerialNumber:'3F10AB7E'})));
        disks.push(O('Win32_LogicalDisk',{DeviceID:'E:',DriveType:5,ProviderName:null,VolumeName:null,Size:null,FreeSpace:null,FileSystem:null,VolumeSerialNumber:null}));}
      return disks;}
    case'win32_quickfixengineering':return[['KB5043080','Security Update',ago(30)],['KB5044284','Update',ago(16)],['KB5043937','Security Update',ago(9)]].map(k=>mk('Microsoft.Management.Infrastructure.CimInstance#root/cimv2/Win32_QuickFixEngineering',{Source:pc,Description:k[1],HotFixID:k[0],InstalledBy:'AUTORITE NT\\Système',InstalledOn:k[2],PSComputerName:null},{__s:k[0]}));
    case'win32_service':return(hostN?svcList(findHost(hostN).self?null:findHost(hostN).n):st.services).map(s=>O('Win32_Service',{ProcessId:s.Status==='Running'?1000+hash32(s.Name)%9000:0,Name:s.Name,StartMode:{Automatic:'Auto',Manual:'Manual',Disabled:'Disabled'}[s.StartType],State:s.Status,Status:'OK',ExitCode:0,DisplayName:s.DisplayName,StartName:'LocalSystem',PathName:'C:\\Windows\\system32\\svchost.exe -k netsvcs -p'}));
    case'win32_startupcommand':return[['OneDrive','"C:\\Program Files\\Microsoft OneDrive\\OneDrive.exe" /background','HKU\\S-1-5-21-...-1115\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run','CONTOSO\\it.tech'],['SecurityHealth','%windir%\\system32\\SecurityHealthSystray.exe','HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run','Public'],['VeeamTray','"C:\\Program Files\\Veeam\\Endpoint Backup\\Veeam.EndPoint.Tray.exe"','HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run','Public'],['ScanAssist','"C:\\Program Files (x86)\\ScanAssist\\ScanAssist.exe" /tray','HKU\\S-1-5-21-...-1115\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run','CONTOSO\\it.tech']].filter(x=>!(hostN&&!findHost(hostN).self&&x[0]==='ScanAssist')).map(x=>O('Win32_StartupCommand',{Name:x[0],Command:x[1],Location:x[2],User:x[3]}));
    case'win32_printer':return[['IMP-RECEP','IMP-RECEP',false],['\\\\SRV-IMPRESSION\\IMP-COMPTA',null,false],['Microsoft Print to PDF',null,true]].map(x=>O('Win32_Printer',{Name:x[0],ShareName:x[1],SystemName:x[0].startsWith('\\\\')?'\\\\SRV-IMPRESSION':pc,Default:x[2],PrinterStatus:x[0]==='IMP-RECEP'?1:3,WorkOffline:false}));
    case'win32_userprofile':{const prof=[['C:\\Users\\it.tech',ago(0,7,58),false,true],['C:\\Users\\jdupont',ago(1,8,10),false,false],['C:\\Users\\stagiaire.ete',ago(400),false,false],['C:\\Users\\cmoreau',ago(45),false,false],['C:\\Windows\\ServiceProfiles\\NetworkService',ago(0),true,true],['C:\\Windows\\system32\\config\\systemprofile',ago(0),true,true]];return prof.map(x=>O('Win32_UserProfile',{LocalPath:x[0],LastUseTime:x[1],Special:x[2],Loaded:x[3],SID:x[2]?'S-1-5-20':DOM.sid+'-'+(1100+hash32(x[0])%40)}));}
    case'win32_product':host(L('(Win32_Product est lent et déclenche une vérification MSI de chaque logiciel : préfère lire la clé de registre Uninstall.)','t-warn'));return[['7-Zip 24.08 (x64 edition)','24.08.00.0','Igor Pavlov'],['Veeam Agent for Microsoft Windows','6.2.0.121','Veeam Software Group GmbH'],['Google Chrome','129.0.6668.90','Google LLC']].map(x=>O('Win32_Product',{Name:x[0],Version:x[1],Vendor:x[2],Caption:x[0],IdentifyingNumber:'{'+guid(x[0]).toUpperCase()+'}'}));
    case'win32_networkadapterconfiguration':return[O('Win32_NetworkAdapterConfiguration',{ServiceName:'e1dexpress',DHCPEnabled:true,Index:1,Description:'Intel(R) Ethernet Connection (17) I219-LM',IPEnabled:true,IPAddress:[hostN?(findHost(hostN)||{}).ip:ME.ip,'fe80::4c1a:9b2e:7d3f:21a5'],IPSubnet:['255.255.255.0','64'],DefaultIPGateway:[ME.gw],DNSServerSearchOrder:ME.dns,MACAddress:ME.mac.replace(/-/g,':'),DHCPServer:'192.168.10.5'}),O('Win32_NetworkAdapterConfiguration',{ServiceName:'Netwtw14',DHCPEnabled:true,Index:2,Description:'Intel(R) Wi-Fi 6E AX211 160MHz',IPEnabled:false,IPAddress:null,IPSubnet:null,DefaultIPGateway:null,DNSServerSearchOrder:null,MACAddress:'70:A8:D3:11:42:9B',DHCPServer:null})];
    case'win32_process':return st.procs.map(p=>O('Win32_Process',{ProcessId:p.Id,Name:p.Name+(p.sys&&/System/.test(p.Name)?'':'.exe'),HandleCount:p.Handles,WorkingSetSize:p.WS,VirtualSize:p.WS*4,CommandLine:p.Path||null,ExecutablePath:p.Path||null}));
    case'win32_share':return[['ADMIN$','C:\\Windows','Administration à distance'],['C$','C:\\','Partage par défaut'],['IPC$','','IPC distant']].map(x=>O('Win32_Share',{Name:x[0],Path:x[1],Description:x[2]}));
    case'win32_battery':return[];
    case'win32_physicalmemory':return[O('Win32_PhysicalMemory',{BankLabel:'BANK 0',Capacity:hw.ram/2*1073741824,DeviceLocator:'DIMM1',Manufacturer:'Samsung',PartNumber:'M378A1K43EB2-CWE',Speed:3200}),O('Win32_PhysicalMemory',{BankLabel:'BANK 1',Capacity:hw.ram/2*1073741824,DeviceLocator:'DIMM2',Manufacturer:'Samsung',PartNumber:'M378A1K43EB2-CWE',Speed:3200})];
    case'win32_diskdrive':return[O('Win32_DiskDrive',{DeviceID:'\\\\.\\PHYSICALDRIVE0',Caption:'Samsung SSD 980 PRO 512GB',Model:'Samsung SSD 980 PRO 512GB',Size:512105932800,SerialNumber:'S69ENF0W123456',Status:'OK'})];
  }
  throw psErr(`Classe non valide « ${cls} »`,'MetadataError','HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand');
}
function wqlToPs(f){return String(f).replace(/<>/g,' -ne ').replace(/>=/g,' -ge ').replace(/<=/g,' -le ').replace(/(^|[^-!<>])=/g,'$1 -eq ').replace(/(^|[^-])>/g,'$1 -gt ').replace(/(^|[^-])</g,'$1 -lt ').replace(/\bLIKE\b/gi,'-like').replace(/\bAND\b/gi,'-and').replace(/\bOR\b/gi,'-or').replace(/\bNOT\b/gi,'-not').replace(/\bTRUE\b/gi,'$true').replace(/\bFALSE\b/gi,'$false').replace(/\bNULL\b/gi,'$null').replace(/'([^']*)'/g,(m,s)=>"'"+s.replace(/%/g,'*').replace(/_/g,'?')+"'");}
function filterObjs(list,filter,scope){if(filter==null||toStr(filter).trim()==='*')return list;const src=isSb(filter)?filter.__sb:toStr(filter);const ast=parseX(lexX(src),src);return list.filter(o=>{const s=newScope(isSb(filter)&&filter.__scope?filter.__scope:scope);s.filterObj=o;try{return truthy(evalNode(ast,s));}catch(e){throw e;}});}
function cimTarget(P,ctx){
  if(P.CimSession!=null){const ss=arr(P.CimSession);return ss.map(s=>{if(!s||!s.__cim)throw psErr('Session CIM non valide.','InvalidArgument','InvalidSession');const h=findHost(s.ComputerName);if(!h||!h.up)throw psErr(`Le serveur RPC n’est pas disponible.`,'ConnectionError','HRESULT 0x800706ba,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand');return h.self?null:h.n;});}
  if(P.ComputerName!=null){return strs(P.ComputerName).map(cn=>{const h=findHost(cn);if(h&&h.self)return null;if(ctx.name==='Get-WmiObject'){if(!h||!h.up)throw psErr('Le serveur RPC n’est pas disponible. (Exception de HRESULT : 0x800706BA)','InvalidOperation','GetWMICOMException,Microsoft.PowerShell.Commands.GetWmiObjectCommand');return h.n;}
    const e=psErr(WINRM_MSG(cn),'ConnectionError','HRESULT 0x80338126,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand');e.hint=WINRM_HINT;throw e;});}
  return[null];
}
function cimGet(P,inp,ctx){
  let cls=P.ClassName!=null?toStr(P.ClassName):null,filter=P.Filter!=null?wqlToPs(toStr(P.Filter)):null;
  if(P.Query!=null){const m=/select\s+(.+?)\s+from\s+(\w+)(?:\s+where\s+(.+))?$/i.exec(toStr(P.Query));if(!m)throw psErr('Requête non valide','InvalidArgument','HRESULT 0x80041017');cls=m[2];if(m[3])filter=wqlToPs(m[3]);}
  if(!cls)throw psErr('Le paramètre ClassName est obligatoire (le simulateur ne peut pas le demander).','InvalidArgument','MissingMandatoryParameter');
  const out=[];
  for(const h of cimTarget(P,ctx)){let list=cimClass(cls,h);if(ctx.name==='Get-WmiObject')list=list.map(o=>{const t=o.__t.replace('Microsoft.Management.Infrastructure.CimInstance#root/cimv2/','System.Management.ManagementObject#root\\cimv2\\');const n=mk(t,Object.assign({},o),{__s:o.__s});return n;});
    list=filterObjs(list,filter,ctx.scope);
    if(P.Property!=null){const ps=strs(P.Property);list=list.map(o=>{const s={};ps.forEach(p=>{const k=Object.keys(o).find(x=>lc(x)===lc(p));if(k)s[k]=o[k];});s.PSComputerName=o.PSComputerName;return mk(o.__t,s);});}
    out.push(...list);}
  return out;
}
def('Get-CimInstance',MODS.cim,'ClassName@Class:p0 Filter Property Query ComputerName@cn CimSession Namespace KeyOnly:sw',(P,inp,ctx)=>cimGet(P,inp,ctx),{alias:['gcim']});
def('Get-WmiObject',MODS.mgmt,'Class@ClassName:p0 Property:p1 Filter Query ComputerName@cn Namespace Credential List:sw',(P,inp,ctx)=>{if(P.Class!=null)P.ClassName=P.Class;return cimGet(P,inp,ctx);},{alias:['gwmi']});
def('Invoke-CimMethod',MODS.cim,'ClassName:p0 MethodName:p1 Arguments@Args InputObject CimSession ComputerName@cn',(P,inp,ctx)=>{const hosts=cimTarget(P,ctx);const m=lc(toStr(P.MethodName||''));const cls=lc(toStr(P.ClassName||(P.InputObject&&P.InputObject.__t)||''));
  if(/win32_process/.test(cls)&&m==='create'){const cl=P.Arguments&&isHt(P.Arguments)?toStr(getMember(P.Arguments,'CommandLine')):'';const pid=(st.nextPid+=12);if(!hosts[0]){const b=cl.split(/[\\ ]/).filter(Boolean).pop().replace(/\.exe$/i,'');st.procs.push({Name:b,Id:pid,SessionName:'Services',SI:0,WS:12582912,CPU:0,Handles:120,Svc:''});}
    return mk('Microsoft.Management.Infrastructure.CimMethodResult',{ProcessId:pid,ReturnValue:0,PSComputerName:hosts[0]});}
  if(/win32_operatingsystem/.test(cls)&&(m==='reboot'||m==='shutdown')){host(L(`(Simulation) ${hosts[0]||'PC-IT-01'} : ${m==='reboot'?'redémarrage':'arrêt'} demandé via CIM.`,'t-warn'));return mk('Microsoft.Management.Infrastructure.CimMethodResult',{ReturnValue:0,PSComputerName:hosts[0]});}
  return mk('Microsoft.Management.Infrastructure.CimMethodResult',{ReturnValue:0,PSComputerName:hosts[0]});});
def('New-CimSessionOption',MODS.cim,'Protocol:p0 UseSsl:sw',(P)=>{const p=lc(toStr(P.Protocol||'Wsman'));return mk(p==='dcom'?'Microsoft.Management.Infrastructure.Options.DComSessionOptions':'Microsoft.Management.Infrastructure.Options.WSManSessionOptions',{Protocol:p==='dcom'?'Dcom':'Wsman',Timeout:'00:00:00',Culture:'fr-FR',UICulture:'fr-FR'},{__s:p==='dcom'?'Microsoft.Management.Infrastructure.Options.DComSessionOptions':'Microsoft.Management.Infrastructure.Options.WSManSessionOptions'});});
def('New-CimSession',MODS.cim,'ComputerName@cn:p0 SessionOption Credential Name Port',(P,inp,ctx)=>{const proto=P.SessionOption&&getMember(P.SessionOption,'Protocol')==='Dcom'?'DCOM':'WSMAN';const out=[];
  for(const cn of strs(P.ComputerName!=null?P.ComputerName:['localhost'])){const h=findHost(cn);
    if(proto==='WSMAN'&&!(h&&h.self)){const e=psErr(WINRM_MSG(cn),'ConnectionError','HRESULT 0x80338126,Microsoft.Management.Infrastructure.CimCmdlets.NewCimSessionCommand');e.hint=WINRM_HINT;ctx.err(e);continue;}
    if(!h||!h.up){ctx.err(psErr('Le serveur RPC n’est pas disponible.','ConnectionError','HRESULT 0x800706ba,Microsoft.Management.Infrastructure.CimCmdlets.NewCimSessionCommand'));continue;}
    const id=st.cim.length+1;const s=mk('Microsoft.Management.Infrastructure.CimSession',{Id:id,Name:P.Name!=null?toStr(P.Name):'CimSession'+id,InstanceId:guid('cim'+id+cn),ComputerName:h.n,Protocol:proto},{__cim:true,__s:h.n});st.cim.push(s);out.push(s);}
  return out;});
def('Get-CimSession',MODS.cim,'Id:p0 ComputerName',()=>st.cim.slice());
def('Remove-CimSession',MODS.cim,'CimSession:p0 Id ComputerName',(P,inp)=>{const ss=P.CimSession!=null?arr(P.CimSession):inp;st.cim=st.cim.filter(s=>!ss.includes(s));return[];});
function evRec(e){return mk('System.Diagnostics.Eventing.Reader.EventLogRecord',{TimeCreated:e.TimeCreated,ProviderName:e.ProviderName,Id:e.Id,LevelDisplayName:e.LevelDisplayName,Message:e.Message,LogName:e.LogName,MachineName:e.MachineName,Level:{Critique:1,Erreur:2,Avertissement:3,Information:4}[e.LevelDisplayName]||4,RecordId:100000+hash32(e.Message+e.TimeCreated)%900000},{__s:'System.Diagnostics.Eventing.Reader.EventLogRecord'});}
function eventsFor(cn,log){const h=cn?findHost(cn):null;const dc=h&&h.dc;let all=[];const logs=log?[log]:['System','Application','Security'];logs.forEach(l=>{const L_=Object.keys(EV.L).find(k=>lc(k)===lc(l));if(dc&&lc(l)==='security'){all=all.concat(EV.DC);return;}if(L_)all=all.concat(EV.L[L_].map(e=>h&&!h.self?Object.assign({},e,{MachineName:h.n+'.contoso.local'}):e));});return all.sort((a,b)=>b.TimeCreated-a.TimeCreated);}
def('Get-WinEvent',MODS.diag,'LogName:p0 MaxEvents FilterHashtable ComputerName@cn ProviderName ListLog Oldest:sw FilterXPath',(P,inp,ctx)=>{
  let cn=null;if(P.ComputerName!=null){const h=findHost(toStr(P.ComputerName));if(!h||!h.up)throw psErr('Le serveur RPC n’est pas disponible.','NotSpecified','System.Diagnostics.Eventing.Reader.EventLogException,Microsoft.PowerShell.Commands.GetWinEventCommand');cn=h.self?null:h.n;}
  if(P.ListLog!=null){return['Application','Security','System','Setup','Windows PowerShell','Microsoft-Windows-PowerShell/Operational','Microsoft-Windows-PrintService/Operational'].filter(n=>nameMatch(n,strs(P.ListLog))).map(n=>mk('System.Diagnostics.Eventing.Reader.EventLogConfiguration',{LogMode:'Circular',MaximumSizeInBytes:20971520,RecordCount:n==='Security'?32411:n==='System'?12044:n==='Application'?8521:120,LogName:n}));}
  let list=[];
  if(P.FilterHashtable!=null){const h=P.FilterHashtable;const g=k=>{const kk=Object.keys(h).find(x=>lc(x)===k);return kk?h[kk]:null;};
    const logs=g('logname');list=(logs?strs(logs):['System','Application','Security']).flatMap(l=>{if(!['system','application','security','setup'].includes(lc(l))){ctx.err(psErr(`Aucun journal des événements n’existe sur l’ordinateur « localhost » correspondant à « ${l} ».`,'ObjectNotFound','NoMatchingLogsFound,Microsoft.PowerShell.Commands.GetWinEventCommand'));return[];}return eventsFor(cn,l);});
    const ids=g('id');if(ids!=null){const s=arr(ids).map(toNum);list=list.filter(e=>s.includes(e.Id));}
    const lvl=g('level');if(lvl!=null){const s=arr(lvl).map(toNum);list=list.filter(e=>s.includes({Critique:1,Erreur:2,Avertissement:3,Information:4}[e.LevelDisplayName]));}
    const pn=g('providername');if(pn!=null)list=list.filter(e=>strs(pn).some(p=>wildRx(p).test(e.ProviderName)));
    const stt=g('starttime');if(stt!=null){const d=toDate(stt);list=list.filter(e=>e.TimeCreated>=d);}
    const et=g('endtime');if(et!=null){const d=toDate(et);list=list.filter(e=>e.TimeCreated<=d);}
  }else{const logs=P.LogName!=null?strs(P.LogName):['System'];
    for(const l of logs){if(!['system','application','security','setup'].includes(lc(l))&&!/powershell/i.test(l)){ctx.err(psErr(`Aucun journal des événements n’existe sur l’ordinateur « localhost » correspondant à « ${l} ».`,'ObjectNotFound','NoMatchingLogsFound,Microsoft.PowerShell.Commands.GetWinEventCommand'));continue;}list=list.concat(eventsFor(cn,l));}
    if(P.ProviderName!=null)list=eventsFor(cn,null).filter(e=>strs(P.ProviderName).some(p=>wildRx(p).test(e.ProviderName)));}
  list.sort((a,b)=>b.TimeCreated-a.TimeCreated);if(P.Oldest)list.reverse();
  if(P.MaxEvents!=null)list=list.slice(0,toNum(P.MaxEvents));
  if(!list.length){ctx.err(notFound('Aucun événement correspondant aux critères de sélection spécifiés n’a été trouvé.','NoMatchingEventsFound,Microsoft.PowerShell.Commands.GetWinEventCommand'));if(P.FilterHashtable&&!cn&&/4740/.test(JSON.stringify(Object.values(P.FilterHashtable).map(toStr))))host(L('(Le 4740 est journalisé sur le contrôleur de domaine PDC, pas sur ce poste : ajoute -ComputerName SRV-AD01.)','t-warn'));return[];}
  return list.map(evRec);
});
def('Get-EventLog',MODS.mgmt,'LogName:p0 Newest EntryType Source InstanceId:p1 After Before ComputerName@cn List:sw Message',(P,inp,ctx)=>{
  if(P.List)return['Application','Security','System','Windows PowerShell'].map(n=>mk('System.Diagnostics.EventLog',{Max:'20 480',Retain:0,OverflowAction:'OverwriteAsNeeded',Entries:n==='Security'?'32 411':'12 044',Log:n}));
  if(P.LogName==null)throw psErr('Le paramètre LogName est obligatoire (le simulateur ne peut pas le demander).','InvalidArgument','MissingMandatoryParameter');
  let cn=null;if(P.ComputerName!=null){const h=findHost(toStr(P.ComputerName));if(!h||!h.up)throw psErr('Le chemin réseau n’a pas été trouvé.','InvalidOperation','System.InvalidOperationException');cn=h.self?null:h.n;}
  let list=eventsFor(cn,toStr(P.LogName));
  const map={Critique:'Error',Erreur:'Error',Avertissement:'Warning',Information:'Information'};
  if(P.EntryType!=null){const s=strs(P.EntryType).map(lc);list=list.filter(e=>s.includes(lc(map[e.LevelDisplayName])));}
  if(P.InstanceId!=null){const s=arr(P.InstanceId).map(toNum);list=list.filter(e=>s.includes(e.Id));}
  if(P.Source!=null)list=list.filter(e=>strs(P.Source).some(p=>wildRx(p).test(e.ProviderName)));
  if(P.After!=null){const d=toDate(P.After);list=list.filter(e=>e.TimeCreated>=d);}
  if(P.Newest!=null)list=list.slice(0,toNum(P.Newest));
  return list.map((e,i)=>mk('System.Diagnostics.EventLogEntry',{Index:30000-i,TimeGenerated:e.TimeCreated,EntryType:map[e.LevelDisplayName],Source:e.ProviderName,InstanceID:e.Id,Message:e.Message,MachineName:e.MachineName},{__s:'System.Diagnostics.EventLogEntry'}));
});
def('Get-HotFix',MODS.mgmt,'Id:p0 ComputerName@cn Description',(P,inp,ctx)=>{let cn=null;if(P.ComputerName!=null){const h=findHost(toStr(P.ComputerName));if(!h||!h.up)throw psErr('Le serveur RPC n’est pas disponible.','InvalidOperation','GetHotFixNoEntriesFound');cn=h.self?null:h.n;}
  let l=cimClass('win32_quickfixengineering',cn).map(o=>mk('System.Management.ManagementObject#root\\cimv2\\Win32_QuickFixEngineering',Object.assign({},o)));if(P.Id!=null)l=l.filter(o=>strs(P.Id).some(i=>lc(i)===lc(o.HotFixID)));return l;});
def('Get-ComputerInfo',MODS.mgmt,'Property:p0',(P)=>{const hw=hostHw('PC-IT-01');const o={WindowsBuildLabEx:'26100.1.amd64fre.ge_release.240331-1435',WindowsCurrentVersion:'6.3',WindowsEditionId:'Professional',WindowsInstallationType:'Client',WindowsProductName:'Windows 10 Pro',WindowsRegisteredOrganization:'Contoso Hôtels',WindowsRegisteredOwner:'Contoso Hôtels',WindowsVersion:'2009',BiosManufacturer:hw.man,BiosSeralNumber:hw.serial,BiosSMBIOSBIOSVersion:'1.21.0',CsDNSHostName:'PC-IT-01',CsDomain:'contoso.local',CsManufacturer:hw.man,CsModel:hw.model,CsName:'PC-IT-01',CsNumberOfLogicalProcessors:hw.lp,CsTotalPhysicalMemory:hw.ram*1073741824-291504128,CsUserName:'CONTOSO\\it.tech',OsName:'Microsoft Windows 11 Professionnel',OsVersion:'10.0.26100',OsBuildNumber:'26100',OsArchitecture:'64 bits',OsLanguage:'fr-FR',OsLastBootUpTime:hw.boot,OsUptime:timespan(new Date()-hw.boot),OsInstallDate:hw.install,OsFreePhysicalMemory:Math.round(hw.ram*1048576*0.46),TimeZone:'(UTC+01:00) Bruxelles, Copenhague, Madrid, Paris',LogonServer:'\\\\SRV-AD01',HyperVisorPresent:true,DeviceGuardSmartStatus:'Off',OsHotFixes:['KB5043080','KB5044284','KB5043937']};
  if(P.Property!=null){const ps=strs(P.Property);const s={};Object.keys(o).filter(k=>ps.some(p=>wildRx(p).test(k))).forEach(k=>s[k]=o[k]);return mk('Microsoft.PowerShell.Commands.ComputerInfo',s);}
  return mk('Microsoft.PowerShell.Commands.ComputerInfo',o);},{alias:['gin']});
function remoteHostsOrSelf(P){return P.ComputerName!=null?strs(P.ComputerName):['localhost'];}
def('Restart-Computer',MODS.mgmt,'ComputerName@cn:p0 Force:sw Wait:sw Protocol Credential Timeout For',(P,inp,ctx)=>{for(const cn of remoteHostsOrSelf(P)){const h=findHost(cn);if(!h||!h.up){ctx.err(psErr(`Échec du redémarrage de l’ordinateur ${cn} avec le message suivant : Le serveur RPC n’est pas disponible.`,'OperationStopped','RestartcomputerFailed,Microsoft.PowerShell.Commands.RestartComputerCommand'));continue;}
  if(ctx.whatif){ctx.wi('Restart-Computer',h.n);continue;}
  if(!P.Force&&h.self)host(L('(Simulation) Ce poste redémarre… (des sessions ouvertes empêcheraient le redémarrage sans -Force)','t-warn'));else host(L(`(Simulation) ${h.self?'Ce poste':h.n} redémarre via ${lc(toStr(P.Protocol||'DCOM'))==='wsman'?'WSMan':'DCOM/WMI (pas besoin de WinRM en 5.1)'}${P.Wait?' ; -Wait attend son retour.':'.'}`,'t-warn'));}return[];});
def('Stop-Computer',MODS.mgmt,'ComputerName@cn:p0 Force:sw',(P,inp,ctx)=>{for(const cn of remoteHostsOrSelf(P)){if(ctx.whatif){ctx.wi('Stop-Computer',cn);continue;}host(L(`(Simulation) Arrêt de ${cn==='localhost'?'ce poste':cn}.`,'t-warn'));}return[];});
def('Rename-Computer',MODS.mgmt,'NewName:p0 ComputerName DomainCredential LocalCredential Restart:sw Force:sw',(P,inp,ctx)=>{if(ctx.whatif){ctx.wi('Rename-Computer',`PC-IT-01 -> ${toStr(P.NewName)}`);return[];}if(!P.Restart)ctx.warn(`Les modifications seront prises en compte après le redémarrage de l’ordinateur PC-IT-01.`);else host(L('(Simulation) Renommage puis redémarrage.','t-warn'));return[];});
def('Add-Computer',MODS.mgmt,'DomainName:p0 Credential OUPath Restart:sw Force:sw NewName',(P,inp,ctx)=>{if(P.Credential==null)host(L('(Simulation) La fenêtre d’identifiants s’ouvrirait : compte autorisé à joindre des postes au domaine.','t-warn'));if(!P.Restart)ctx.warn('Les modifications seront prises en compte après le redémarrage de l’ordinateur PC-IT-01.');else host(L('(Simulation) Jonction au domaine puis redémarrage.','t-warn'));return[];});
def('Remove-Computer',MODS.mgmt,'UnjoinDomainCredential WorkgroupName Restart:sw Force:sw',(P,inp,ctx)=>{ctx.warn('Les modifications seront prises en compte après le redémarrage de l’ordinateur PC-IT-01.');return[];});
def('Test-ComputerSecureChannel',MODS.mgmt,'Repair:sw Server Credential',(P,inp,ctx)=>{if(P.Repair)ctx.verbose('Le canal sécurisé a été réparé.');return true;});
def('Reset-ComputerMachinePassword',MODS.mgmt,'Server Credential',()=>[]);
def('Get-ExecutionPolicy',MODS.sec,'Scope:p0 List:sw',(P)=>{if(P.List)return['MachinePolicy','UserPolicy','Process','CurrentUser','LocalMachine'].map(s=>mk('Microsoft.PowerShell.ExecutionPolicy',{Scope:s,ExecutionPolicy:st.execPolicy[s]}));if(P.Scope!=null){const k=Object.keys(st.execPolicy).find(x=>lc(x)===lc(toStr(P.Scope)));return st.execPolicy[k];}return effectivePolicy();});
def('Set-ExecutionPolicy',MODS.sec,'ExecutionPolicy:p0 Scope:p1 Force:sw',(P,inp,ctx)=>{const v=toStr(P.ExecutionPolicy);const ok=['Restricted','AllSigned','RemoteSigned','Unrestricted','Bypass','Undefined','Default'].find(x=>lc(x)===lc(v));if(!ok)throw psErr(`Impossible de lier le paramètre « ExecutionPolicy ». Impossible de convertir la valeur « ${v} » en type « Microsoft.PowerShell.ExecutionPolicy ». Les valeurs d’énumération valides sont « Unrestricted, RemoteSigned, AllSigned, Restricted, Default, Bypass, Undefined ».`,'InvalidArgument','CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand');
  const sc=P.Scope!=null?Object.keys(st.execPolicy).find(x=>lc(x)===lc(toStr(P.Scope))):'LocalMachine';if(!sc||/Policy$/.test(sc))throw psErr('Impossible de définir la stratégie pour cette étendue : elle est contrôlée par une stratégie de groupe.','InvalidArgument','CantSetGroupPolicy');
  if(ctx.whatif){ctx.wi('Set-ExecutionPolicy',ok);return[];}
  if(!P.Force){host(L(''));host(L('Modification de la stratégie d’exécution'));host(L('La stratégie d’exécution permet de vous prémunir contre les scripts que vous jugez non fiables. En modifiant la stratégie d’exécution, vous vous exposez aux risques de sécurité décrits dans la rubrique d’aide about_Execution_Policies à l’adresse https://go.microsoft.com/fwlink/?LinkID=135170. Voulez-vous modifier la stratégie d’exécution ?'));host(L('[O] Oui  [T] Oui pour tout  [N] Non  [U] Non pour tout  [S] Suspendre  [?] Aide (la valeur par défaut est « N ») : O'));}
  st.execPolicy[sc]=ok==='Default'?'Undefined':ok;return[];});
def('Get-Volume',MODS.store,'DriveLetter:p0 FileSystemLabel',(P)=>{const v=[['C','OS','NTFS','Fixed',FREE.C,548682067968],['D','DATA','NTFS','Fixed',FREE.D,1000202039296],['E','','Unknown','CD-ROM',0,0]];return v.filter(x=>nameMatch(x[0],strs(P.DriveLetter))).map(x=>mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/Microsoft/Windows/Storage/MSFT_Volume',{DriveLetter:x[0],FriendlyName:x[1],FileSystemType:x[2],DriveType:x[3],HealthStatus:'Healthy',OperationalStatus:'OK',SizeRemaining:x[4],Size:x[5]}));});
def('Get-Disk',MODS.store,'Number:p0',()=>[mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/Microsoft/Windows/Storage/MSFT_Disk',{Number:0,FriendlyName:'Samsung SSD 980 PRO 512GB',SerialNumber:'S69ENF0W123456',HealthStatus:'Healthy',OperationalStatus:'Online',Size:512105932800,PartitionStyle:'GPT'}),mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/Microsoft/Windows/Storage/MSFT_Disk',{Number:1,FriendlyName:'WDC WD10EZEX-08WN4A0',SerialNumber:'WD-WCC6Y4KNDZ12',HealthStatus:'Healthy',OperationalStatus:'Online',Size:1000204886016,PartitionStyle:'GPT'})]);
def('Get-PhysicalDisk',MODS.store,'',()=>[mk('PhysicalDisk',{Number:0,FriendlyName:'Samsung SSD 980 PRO 512GB',MediaType:'SSD',HealthStatus:'Healthy',Size:512105932800}),mk('PhysicalDisk',{Number:1,FriendlyName:'WDC WD10EZEX-08WN4A0',MediaType:'HDD',HealthStatus:'Healthy',Size:1000204886016})]);
const PRINTERS=[['IMP-RECEP','PC-IT-01','Connection','HP Universal Printing PCL 6','\\\\SRV-IMPRESSION\\IMP-RECEP',false],['\\\\SRV-IMPRESSION\\IMP-COMPTA','SRV-IMPRESSION','Connection','Canon Generic Plus PCL6','\\\\SRV-IMPRESSION\\IMP-COMPTA',false],['Microsoft Print to PDF','','Local','Microsoft Print To PDF','PORTPROMPT:',false]];
def('Get-Printer',MODS.print,'Name:p0 ComputerName@cn',(P)=>PRINTERS.filter(p=>nameMatch(p[0],strs(P.Name))).map(p=>mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/MSFT_Printer',{Name:p[0],ComputerName:p[1],Type:p[2],DriverName:p[3],PortName:p[4],Shared:p[5],Published:false,PrinterStatus:p[0]==='IMP-RECEP'&&st.printJobs.some(j=>j.JobStatus==='Error')?'Error':'Normal'})));
def('Get-PrintJob',MODS.print,'PrinterName:p0 ID ComputerName',(P)=>{if(P.PrinterName==null)throw psErr('Le paramètre PrinterName est obligatoire.','InvalidArgument','MissingMandatoryParameter');return st.printJobs.filter(j=>lc(j.PrinterName)===lc(toStr(P.PrinterName).replace(/^\\\\SRV-IMPRESSION\\/i,''))).map(j=>mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/MSFT_PrintJob',{Id:j.Id,ComputerName:'',PrinterName:j.PrinterName,DocumentName:j.DocumentName,SubmittedTime:j.SubmittedTime,JobStatus:j.JobStatus,UserName:j.UserName,Size:j.Size},{__job:j}));});
def('Remove-PrintJob',MODS.print,'PrinterName:p0 ID InputObject',(P,inp)=>{const ids=P.ID!=null?arr(P.ID).map(toNum):(P.InputObject!=null?arr(P.InputObject):inp).map(o=>toNum(getMember(o,'Id')));st.printJobs=st.printJobs.filter(j=>!ids.includes(j.Id));return[];});
def('Restart-PrintJob',MODS.print,'PrinterName:p0 ID InputObject',()=>[]);
function taskObj(t){return mk('Microsoft.Management.Infrastructure.CimInstance#Root/Microsoft/Windows/TaskScheduler/MSFT_ScheduledTask',{TaskPath:t.TaskPath,TaskName:t.TaskName,State:t.State,Author:'CONTOSO\\it.tech',Description:t.Desc||'',URI:t.TaskPath+t.TaskName,Actions:[t.Run],Triggers:[t.Sched]},{__task:t});}
def('Get-ScheduledTask',MODS.sched,'TaskName:p0 TaskPath',(P,inp,ctx)=>{const l=st.tasks.filter(t=>nameMatch(t.TaskName,strs(P.TaskName)));if(P.TaskName!=null&&!l.length&&!strs(P.TaskName).some(hasWild))throw notFound(`Aucune ressource MSFT_ScheduledTask trouvée avec la propriété « TaskName » égale à « ${toStr(P.TaskName)} ».`,'CmdletizationQuery_NotFound_TaskName,Get-ScheduledTask');return l.map(taskObj);});
def('Get-ScheduledTaskInfo',MODS.sched,'TaskName:p0 InputObject',(P,inp)=>{const names=P.TaskName!=null?strs(P.TaskName):inp.map(o=>getMember(o,'TaskName'));return st.tasks.filter(t=>names.some(n=>lc(n)===lc(t.TaskName))).map(t=>mk('Microsoft.Management.Infrastructure.CimInstance#Root/Microsoft/Windows/TaskScheduler/MSFT_TaskDynamicInfo',{LastRunTime:t.Last,LastTaskResult:t.Result,NextRunTime:t.Next,NumberOfMissedRuns:0,TaskName:t.TaskName,TaskPath:t.TaskPath}));});
def('Start-ScheduledTask',MODS.sched,'TaskName:p0 InputObject',(P,inp)=>{const names=P.TaskName!=null?strs(P.TaskName):inp.map(o=>getMember(o,'TaskName'));st.tasks.filter(t=>names.some(n=>lc(n)===lc(t.TaskName))).forEach(t=>{t.Last=new Date();t.Result=0;});return[];});
def('Disable-ScheduledTask',MODS.sched,'TaskName:p0',(P)=>st.tasks.filter(t=>lc(t.TaskName)===lc(toStr(P.TaskName))).map(t=>{t.State='Disabled';return taskObj(t);}));
def('Enable-ScheduledTask',MODS.sched,'TaskName:p0',(P)=>st.tasks.filter(t=>lc(t.TaskName)===lc(toStr(P.TaskName))).map(t=>{t.State='Ready';return taskObj(t);}));
def('Unregister-ScheduledTask',MODS.sched,'TaskName:p0 Confirm:sw',(P)=>{if(P.Confirm!==false){host(L('Confirmer'));host(L(`Voulez-vous vraiment effectuer cette action ? Opération « Supprimer » en cours sur la cible « ${toStr(P.TaskName)} ». [O] Oui : O`));}st.tasks=st.tasks.filter(t=>lc(t.TaskName)!==lc(toStr(P.TaskName)));return[];});
def('New-ScheduledTaskAction',MODS.sched,'Execute:p0 Argument:p1 WorkingDirectory',(P)=>mk('Microsoft.Management.Infrastructure.CimInstance#Root/Microsoft/Windows/TaskScheduler/MSFT_TaskExecAction',{Id:null,Arguments:P.Argument!=null?toStr(P.Argument):null,Execute:toStr(P.Execute),WorkingDirectory:P.WorkingDirectory!=null?toStr(P.WorkingDirectory):null}));
def('New-ScheduledTaskTrigger',MODS.sched,'Daily:sw Weekly:sw Once:sw AtStartup:sw AtLogOn:sw At DaysOfWeek DaysInterval',(P)=>mk('Microsoft.Management.Infrastructure.CimInstance#Root/Microsoft/Windows/TaskScheduler/MSFT_TaskTrigger',{Enabled:true,StartBoundary:P.At!=null?toStr(P.At):'',Type:P.Daily?'Daily':P.Weekly?'Weekly':P.AtStartup?'AtStartup':P.AtLogOn?'AtLogOn':'Once',DaysOfWeek:P.DaysOfWeek!=null?strs(P.DaysOfWeek):null}));
def('New-ScheduledTaskPrincipal',MODS.sched,'UserId:p0 LogonType RunLevel',(P)=>mk('Principal',{UserId:toStr(P.UserId),LogonType:P.LogonType!=null?toStr(P.LogonType):'Interactive',RunLevel:P.RunLevel!=null?toStr(P.RunLevel):'Limited'}));
def('Register-ScheduledTask',MODS.sched,'TaskName:p0 Action Trigger Principal User Password RunLevel Description TaskPath Force:sw',(P)=>{const tn=toStr(P.TaskName);if(st.tasks.some(t=>lc(t.TaskName)===lc(tn))&&!P.Force)throw psErr(`Impossible de créer un fichier déjà existant. (La tâche « ${tn} » existe : ajoute -Force.)`,'ResourceExists','HRESULT 0x800700b7,Register-ScheduledTask');
  st.tasks=st.tasks.filter(t=>lc(t.TaskName)!==lc(tn));const a=P.Action;const tr=P.Trigger;const t={TaskName:tn,TaskPath:'\\',State:'Ready',Next:ago(-1,22,0),Last:null,Result:267011,Run:a?(toStr(getMember(a,'Execute'))+' '+toStr(getMember(a,'Arguments')||'')).trim():'',User:P.User!=null?toStr(P.User):(P.Principal?toStr(getMember(P.Principal,'UserId')):'CONTOSO\\it.tech'),Sched:tr?toStr(getMember(tr,'Type'))+' '+toStr(getMember(tr,'StartBoundary')):'',Desc:P.Description!=null?toStr(P.Description):''};st.tasks.push(t);return taskObj(t);});
def('Get-WindowsCapability',MODS.dism,'Name:p0 Online:sw LimitAccess:sw',(P)=>{if(!P.Online)throw psErr('Le paramètre -Online est requis pour interroger le Windows en cours d’exécution.','InvalidArgument','MissingOnline');const caps=[['Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0','Installed'],['Rsat.GroupPolicy.Management.Tools~~~~0.0.1.0','Installed'],['Rsat.Dns.Tools~~~~0.0.1.0','NotPresent'],['Rsat.DHCP.Tools~~~~0.0.1.0','NotPresent'],['Rsat.ServerManager.Tools~~~~0.0.1.0','Installed'],['Rsat.FileServices.Tools~~~~0.0.1.0','NotPresent'],['Rsat.PrintManagement.Tools~~~~0.0.1.0','Installed'],['OpenSSH.Client~~~~0.0.1.0','Installed'],['WMIC~~~~','NotPresent']];return caps.filter(c=>nameMatch(c[0],strs(P.Name))).map(c=>mk('Microsoft.Dism.Commands.BasicCapabilityObject',{Name:c[0],State:c[1]}));});
def('Add-WindowsCapability',MODS.dism,'Name:p0 Online:sw Source LimitAccess:sw',(P)=>{host(L(`(Simulation) Installation de ${toStr(P.Name)} depuis Windows Update… terminé.`,'t-warn'));return mk('Microsoft.Dism.Commands.ImageObject',{Path:'',Online:true,RestartNeeded:false});});
def('Get-AppxPackage',MODS.appx,'Name:p0 AllUsers:sw',(P)=>[['Microsoft.WindowsCalculator','11.2409.0.0'],['Microsoft.WindowsNotepad','11.2409.9.0'],['Microsoft.XboxGamingOverlay','7.124.8261.0'],['MicrosoftTeams','24243.1309.3132.617'],['Microsoft.BingWeather','4.53.61000.0']].filter(a=>nameMatch(a[0],strs(P.Name))).map(a=>mk('Microsoft.Windows.Appx.PackageManager.Commands.AppxPackage',{Name:a[0],Publisher:'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US',Architecture:'X64',Version:a[1],PackageFullName:a[0]+'_'+a[1]+'_x64__8wekyb3d8bbwe',InstallLocation:'C:\\Program Files\\WindowsApps\\'+a[0]+'_'+a[1]+'_x64__8wekyb3d8bbwe',IsFramework:false,SignatureKind:'Store',Status:'Ok'})));
def('Remove-AppxPackage',MODS.appx,'Package:p0 AllUsers:sw',(P,inp,ctx)=>{if(ctx.whatif)ctx.wi('Remove-AppxPackage',toStr(P.Package||'?'));return[];});
const MODULES=[['Manifest','3.1.0.0','Microsoft.PowerShell.Management','{Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}'],['Manifest','3.1.0.0','Microsoft.PowerShell.Utility','{Add-Member, Add-Type, Clear-Variable, Compare-Object...}'],['Script','2.3.6','PSReadline','{Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}']];
const MODULES_AV=[['Manifest','1.0.1.0','ActiveDirectory','{Add-ADCentralAccessPolicyMember, Add-ADComputerServiceAccount, Add-ADDomainControllerPasswordReplicationPolicy, Add-ADFineGrainedPasswordPolicySubject...}'],['Manifest','1.0.0.0','CimCmdlets','{Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance, Get-CimSession...}'],['Manifest','1.0.0.0','DnsClient','{Resolve-DnsName, Clear-DnsClientCache, Get-DnsClient, Get-DnsClientCache...}'],['Manifest','1.0.0.0','NetTCPIP','{Get-NetIPAddress, Get-NetIPConfiguration, Test-NetConnection...}'],['Manifest','1.0.0.0','PrintManagement','{Add-Printer, Get-Printer, Get-PrintJob, Remove-PrintJob...}'],['Manifest','1.0.0.0','ScheduledTasks','{Get-ScheduledTask, Register-ScheduledTask, Start-ScheduledTask...}'],['Manifest','1.0.0.0','GroupPolicy','{Get-GPO, Get-GPResultantSetOfPolicy, Invoke-GPUpdate, New-GPLink...}']];
st.mods=new Set(['microsoft.powershell.management','microsoft.powershell.utility','psreadline']);
def('Get-Module',MODS.core,'Name:p0 ListAvailable:sw All:sw',(P)=>{const list=P.ListAvailable?MODULES.concat(MODULES_AV):MODULES.concat(MODULES_AV.filter(m=>st.mods.has(lc(m[2]))));return list.filter(m=>nameMatch(m[2],strs(P.Name))).map(m=>mk('System.Management.Automation.PSModuleInfo',{ModuleType:m[0],Version:m[1],Name:m[2],ExportedCommands:m[3].replace(/[{}]/g,'').split(', ')}));},{alias:['gmo']});
def('Import-Module',MODS.core,'Name:p0 Force:sw PassThru:sw',(P,inp,ctx)=>{strs(P.Name).forEach(n=>{const m=MODULES_AV.find(x=>lc(x[2])===lc(n));if(!m){ctx.err(notFound(`Le module « ${n} » spécifié n’a pas été chargé, car aucun fichier de module valide n’a été trouvé dans aucun répertoire de module.`,'Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand','ResourceUnavailable'));return;}st.mods.add(lc(n));});return[];},{alias:['ipmo']});
def('Install-Module',MODS.psget,'Name:p0 Scope Force:sw Repository AllowClobber:sw',(P)=>{host(L('Référentiel non approuvé'));host(L('Vous installez les modules à partir d’un référentiel non approuvé. Si vous approuvez ce référentiel, modifiez sa valeur InstallationPolicy en exécutant l’applet de commande Set-PSRepository. Voulez-vous vraiment installer les modules à partir de « PSGallery » ?'));host(L('[O] Oui  [T] Oui pour tout  [N] Non  [U] Non pour tout  [S] Suspendre  [?] Aide (la valeur par défaut est « N ») : O'));host(L(`(Simulation) Module ${toStr(P.Name)} installé depuis PowerShell Gallery${P.Scope?' pour l’étendue '+toStr(P.Scope):''}.`,'t-warn'));return[];});
def('Find-Module',MODS.psget,'Name:p0',(P)=>[mk('PSRepositoryItemInfo',{Version:'2.2.5',Name:toStr(P.Name||'PSWindowsUpdate'),Repository:'PSGallery',Description:'Module de la galerie PowerShell (simulation).'})]);
def('Start-Transcript',MODS.core,'Path:p0 Append:sw OutputDirectory IncludeInvocationHeader:sw',(P)=>{const d=new Date();const p=P.Path!=null?toStr(P.Path):`C:\\Users\\it.tech\\Documents\\PowerShell_transcript.PC-IT-01.${fakeHash(String(d),8).toLowerCase()}.${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}.txt`;
  writeFile(p,['**********************','Début de la transcription de Windows PowerShell',`Heure de début : ${fmtDate(d,'yyyyMMddHHmmss')}`,'Nom d’utilisateur : CONTOSO\\it.tech','Ordinateur : PC-IT-01 (Microsoft Windows NT 10.0.26100.0)','**********************'].join('\n'),!!P.Append);st.transcript=showLoc(resolve(p));return `Transcription démarrée, le fichier de sortie est ${st.transcript}`;});
def('Stop-Transcript',MODS.core,'',()=>{if(!st.transcript)throw psErr('Une erreur s’est produite lors de l’arrêt de la transcription : L’hôte n’est pas en cours de transcription.','InvalidOperation','InvalidOperation,Microsoft.PowerShell.Commands.StopTranscriptCommand');const p=st.transcript;writeFile(p,['**********************','Fin de la transcription de Windows PowerShell','**********************'].join('\n'),true);st.transcript=null;return `Transcription arrêtée, le fichier de sortie est ${p}`;});
def('Get-Credential',MODS.sec,'Credential@UserName:p0 Message',(P)=>{host(L('(Simulation) La fenêtre « Demande d’informations d’identification » s’ouvre ; le mot de passe est saisi masqué.','t-warn'));return mk('System.Management.Automation.PSCredential',{UserName:P.Credential!=null?toStr(P.Credential):'CONTOSO\\it.tech',Password:mk('System.Security.SecureString',{Length:14},{__s:'System.Security.SecureString'})},{__s:'System.Management.Automation.PSCredential'});});
def('ConvertTo-SecureString',MODS.sec,'String:p0 AsPlainText:sw Force:sw Key SecureKey',(P)=>{if(P.AsPlainText&&!P.Force)throw psErr('Le système ne peut pas protéger l’entrée de texte brut. Pour supprimer cet avertissement et convertir le texte brut en SecureString, entrez à nouveau la commande en spécifiant le paramètre Force. Pour plus d’informations, tapez Get-Help ConvertTo-SecureString.','InvalidArgument','ImportSecureString_InvalidArgument,Microsoft.PowerShell.Commands.ConvertToSecureStringCommand');return mk('System.Security.SecureString',{Length:toStr(P.String).length},{__s:'System.Security.SecureString'});});
def('ConvertFrom-SecureString',MODS.sec,'SecureString:p0 Key AsPlainText:sw',(P)=>P.AsPlainText?'(PowerShell 7 uniquement : -AsPlainText)':'01000000d08c9ddf0115d1118c7a00c04fc297eb01000000'+fakeHash('ss',96).toLowerCase());
def('Clear-RecycleBin',MODS.mgmt,'DriveLetter:p0 Force:sw',(P,inp,ctx)=>{if(!P.Force){host(L('Confirmer'));host(L('Voulez-vous vraiment effectuer cette action ? Opération « Clear-RecycleBin » en cours sur la cible « Tout le contenu de la Corbeille ». [O] Oui : O'));}host(L('(Simulation) Corbeille vidée.','t-warn'));return[];});
def('Invoke-WebRequest',MODS.util,'Uri:p0 OutFile Method UseBasicParsing:sw Headers Body Credential UseDefaultCredentials:sw TimeoutSec',(P,inp,ctx)=>{const u=toStr(P.Uri);host(L('(Simulation : le bac à sable n’a pas d’accès Internet réel.)','t-warn'));if(P.OutFile!=null){const f=writeFile(toStr(P.OutFile),'');f.bin=true;f.size=4718592;f.zone=true;return[];}return mk('Microsoft.PowerShell.Commands.HtmlWebResponseObject',{StatusCode:200,StatusDescription:'OK',Content:'<!DOCTYPE html><html><head><title>Page simulée</title></head>...',RawContent:'HTTP/1.1 200 OK',Headers:'{[Content-Type, text/html]}',RawContentLength:1256});},{alias:['iwr','curl','wget']});
def('Invoke-RestMethod',MODS.util,'Uri:p0 Method Headers Body',(P)=>{const u=lc(toStr(P.Uri));if(/ipify/.test(u))return '82.64.112.34';return mk('System.Management.Automation.PSCustomObject',{status:'ok',source:'simulation'});},{alias:['irm']});
/* comptes locaux */
function luObj(u){return mk('Microsoft.PowerShell.Commands.LocalUser',{Name:u.Name,Enabled:u.Enabled,Description:u.Description,FullName:u.FullName||'',PasswordLastSet:u.PasswordLastSet||ago(60),LastLogon:u.Enabled?ago(5):null,SID:'S-1-5-21-1004336348-1177238915-682003330-'+(500+st.localUsers.indexOf(u)),PrincipalSource:'Local',ObjectClass:'Utilisateur'},{__s:u.Name});}
def('Get-LocalUser',MODS.local,'Name:p0 SID',(P,inp,ctx)=>{const pats=strs(P.Name);const l=st.localUsers.filter(u=>nameMatch(u.Name,pats));if(pats.length&&!l.length&&!pats.some(hasWild))throw notFound(`Utilisateur ${pats[0]} introuvable.`,'UserNotFound,Microsoft.PowerShell.Commands.GetLocalUserCommand');return l.map(luObj);},{alias:['glu']});
def('New-LocalUser',MODS.local,'Name:p0 Password FullName Description NoPassword:sw AccountNeverExpires:sw PasswordNeverExpires:sw',(P,inp,ctx)=>{const n=toStr(P.Name);if(st.localUsers.some(u=>lc(u.Name)===lc(n)))throw psErr(`L’utilisateur ${n} existe déjà.`,'ResourceExists','UserExists,Microsoft.PowerShell.Commands.NewLocalUserCommand');if(P.Password!=null&&typeof P.Password==='string')throw psErr('Impossible de lier le paramètre « Password ». Impossible de convertir la valeur « '+P.Password+' » du type « System.String » en type « System.Security.SecureString ».','InvalidArgument','CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.NewLocalUserCommand');if(ctx.whatif){ctx.wi('Nouvel utilisateur local',n);return[];}const u={Name:n,Enabled:true,Description:P.Description!=null?toStr(P.Description):'',FullName:P.FullName!=null?toStr(P.FullName):'',PasswordLastSet:new Date()};st.localUsers.push(u);return luObj(u);},{alias:['nlu']});
function luSet(P,f){strs(P.Name).forEach(n=>{const u=st.localUsers.find(x=>lc(x.Name)===lc(n));if(!u)throw notFound(`Utilisateur ${n} introuvable.`,'UserNotFound');f(u);});return[];}
def('Enable-LocalUser',MODS.local,'Name:p0',(P)=>luSet(P,u=>u.Enabled=true),{alias:['elu']});
def('Disable-LocalUser',MODS.local,'Name:p0',(P)=>luSet(P,u=>u.Enabled=false),{alias:['dlu']});
def('Set-LocalUser',MODS.local,'Name:p0 Password Description FullName PasswordNeverExpires',(P)=>luSet(P,u=>{if(P.Description!=null)u.Description=toStr(P.Description);if(P.FullName!=null)u.FullName=toStr(P.FullName);if(P.Password!=null)u.PasswordLastSet=new Date();}),{alias:['slu']});
def('Remove-LocalUser',MODS.local,'Name:p0',(P,inp,ctx)=>{strs(P.Name).forEach(n=>{if(ctx.whatif){ctx.wi('Supprimer l’utilisateur local',n);return;}st.localUsers=st.localUsers.filter(u=>lc(u.Name)!==lc(n));});return[];},{alias:['rlu']});
def('Get-LocalGroup',MODS.local,'Name:p0',(P)=>Object.values(st.localGroups).filter(g=>nameMatch(g.name,strs(P.Name))).map(g=>mk('Microsoft.PowerShell.Commands.LocalGroup',{Name:g.name,Description:g.desc},{__s:g.name})),{alias:['glg']});
function lgFind(n){const g=st.localGroups[lc(toStr(n))];if(!g)throw notFound(`Le groupe ${toStr(n)} est introuvable.`,'GroupNotFound,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand');return g;}
def('Get-LocalGroupMember',MODS.local,'Group@Name:p0 Member:p1',(P)=>{const g=lgFind(P.Group);return g.members.filter(m=>nameMatch(m.n,strs(P.Member).map(x=>'*'+x))).map(m=>mk('Microsoft.PowerShell.Commands.LocalPrincipal',{ObjectClass:m.c,Name:m.n,PrincipalSource:m.src,SID:m.src==='Local'?'S-1-5-21-1004336348-1177238915-682003330-500':DOM.sid+'-'+(hash32(m.n)%900+1100)},{__s:m.n}));},{alias:['glgm']});
def('Add-LocalGroupMember',MODS.local,'Group@Name:p0 Member:p1',(P,inp,ctx)=>{const g=lgFind(P.Group);strs(P.Member).forEach(m=>{const full=m.includes('\\')?m:(st.localUsers.some(u=>lc(u.Name)===lc(m))?'PC-IT-01\\'+m:'CONTOSO\\'+m);if(g.members.some(x=>lc(x.n)===lc(full))){ctx.err(psErr(`${full} est déjà membre du groupe ${g.name}.`,'ResourceExists','MemberExists,Microsoft.PowerShell.Commands.AddLocalGroupMemberCommand'));return;}if(ctx.whatif){ctx.wi('Ajouter un membre',`${full} -> ${g.name}`);return;}g.members.push({n:full,c:adGroup(m.split('\\').pop())?'Groupe':'Utilisateur',src:full.startsWith('PC-IT-01')?'Local':'ActiveDirectory'});});return[];},{alias:['algm']});
def('Remove-LocalGroupMember',MODS.local,'Group@Name:p0 Member:p1',(P,inp,ctx)=>{const g=lgFind(P.Group);strs(P.Member).forEach(m=>{const i=g.members.findIndex(x=>lc(x.n)===lc(m)||lc(x.n).endsWith('\\'+lc(m)));if(i<0){ctx.err(notFound(`Le principal ${m} n’est pas membre du groupe ${g.name}.`,'PrincipalNotFound'));return;}g.members.splice(i,1);});return[];},{alias:['rlgm']});
/* accès distant (WinRM) */
function winrmFail(cn,ctx,name){const e=psErr(WINRM_MSG(cn),'OpenError','WinRMOperationTimeout,PSSessionStateBroken');e.cmd=name;e.hint=WINRM_HINT;throw e;}
def('Enter-PSSession',MODS.core,'ComputerName@cn:p0 Credential Session',(P,inp,ctx)=>winrmFail(toStr(P.ComputerName),ctx,'Enter-PSSession'),{alias:['etsn']});
def('New-PSSession',MODS.core,'ComputerName@cn:p0 Credential Name',(P,inp,ctx)=>{const cn=strs(P.ComputerName)[0]||'localhost';const h=findHost(cn);if(h&&h.self){winrmFail(cn,ctx,'New-PSSession');}winrmFail(cn,ctx,'New-PSSession');},{alias:['nsn']});
def('Invoke-Command',MODS.core,'ScriptBlock:p0 ComputerName@cn Session Credential ArgumentList@Args FilePath AsJob:sw',(P,inp,ctx)=>{if(P.ComputerName!=null||P.Session!=null){const cn=P.ComputerName!=null?strs(P.ComputerName)[0]:'session';winrmFail(cn,ctx,'Invoke-Command');}if(!P.ScriptBlock)return[];return callSb(P.ScriptBlock,null,{args:arr(P.ArgumentList)});},{alias:['icm']});
def('Test-WSMan',MODS.core,'ComputerName:p0',(P)=>{const cn=P.ComputerName!=null?toStr(P.ComputerName):'localhost';throw Object.assign(psErr(`<f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150858770" Machine="PC-IT-01"><f:Message>Le client ne peut pas se connecter à la destination spécifiée dans la demande (${cn}). Vérifiez que le service sur la destination est en cours d’exécution et accepte les demandes.</f:Message></f:WSManFault>`,'InvalidOperation','WsManError,Microsoft.WSMan.Management.TestWSManCommand'),{hint:WINRM_HINT});});

/* =========================================================
   Cmdlets : réseau
   ========================================================= */
def('Test-Connection',MODS.mgmt,'ComputerName@cn@Destination:p0 Count BufferSize@Size Quiet:sw Delay Source TimeToLive',(P,inp,ctx)=>{
  const cns=P.ComputerName!=null?strs(P.ComputerName):inp.map(toStr);const n=P.Count!=null?toNum(P.Count):4;const out=[];
  for(const cn of cns){const h=findHost(cn);const up=st.ipOk&&h&&h.up&&!h.icmpBlocked;
    if(P.Quiet){out.push(!!up);continue;}
    if(!up){ctx.err(psErr(`Échec de test de connexion avec l’ordinateur « ${cn} » : Erreur due à un manque de ressources`,'ResourceUnavailable','TestConnectionException,Microsoft.PowerShell.Commands.TestConnectionCommand'));continue;}
    for(let i=0;i<n;i++)out.push(mk('System.Management.ManagementObject#root\\cimv2\\Win32_PingStatus',{Source:'PC-IT-01',Destination:cn,IPV4Address:h.ip,IPV6Address:'',Bytes:P.BufferSize!=null?toNum(P.BufferSize):32,ResponseTime:h.ext?11+i%3:(h.self?0:1),StatusCode:0},{__s:'\\\\PC-IT-01\\root\\cimv2:Win32_PingStatus.Address="'+cn+'"'}));}
  return out;});
const PORTNAMES={RDP:3389,SMB:445,HTTP:80,WINRM:5985};
def('Test-NetConnection',MODS.net,'ComputerName@cn@RemoteAddress:p0 Port CommonTCPPort InformationLevel TraceRoute:sw Hops',(P,inp,ctx)=>{
  const cn=P.ComputerName!=null?toStr(P.ComputerName):'internetbeacon.msedge.net';const h=findHost(cn)||(cn==='internetbeacon.msedge.net'?{n:cn,ip:'13.107.4.52',up:true,ext:true,ports:[80,443]}:null);
  const port=P.Port!=null?toNum(P.Port):P.CommonTCPPort!=null?PORTNAMES[toStr(P.CommonTCPPort).toUpperCase()]:null;const quiet=lc(toStr(P.InformationLevel||''))==='quiet',det=lc(toStr(P.InformationLevel||''))==='detailed';
  if(!h){ctx.warn(`Name resolution of ${cn} failed`);return mk('TestNetConnectionResult',{ComputerName:cn,RemoteAddress:null,InterfaceAlias:null,SourceAddress:null,PingSucceeded:false});}
  const up=st.ipOk&&h.up;
  if(port!=null){const ok=up&&(h.ports||[]).includes(port);if(!ok){ctx.warn(`TCP connect to (${h.ip} : ${port}) failed`);if(!up&&!h.icmpBlocked)ctx.warn(`Ping to ${cn} failed with status: TimedOut`);}
    if(quiet)return ok;
    const o={ComputerName:cn,RemoteAddress:h.ip,RemotePort:port,InterfaceAlias:'Ethernet',SourceAddress:ME.ip};if(det){o.NameResolutionResults=h.ip;o.MatchingIPsecRules='';o.NetworkIsolationContext='Private Network';o.IsAdmin=true;o.NetRoute='(NextHop) : '+(h.ext?ME.gw:'0.0.0.0');}if(!ok&&up)o.PingSucceeded=true;if(!ok&&up)o.PingReplyDetails='(RTT) : 1 ms';o.TcpTestSucceeded=ok;return mk('TestNetConnectionResult',o);}
  const pingOk=up&&!h.icmpBlocked;if(!pingOk)ctx.warn(`Ping to ${cn} failed with status: TimedOut`);if(quiet)return pingOk;
  const o={ComputerName:cn,RemoteAddress:h.ip,InterfaceAlias:'Ethernet',SourceAddress:ME.ip,PingSucceeded:pingOk,PingReplyDetails:'(RTT) : '+(pingOk?(h.ext?'12':'1')+' ms':'0 ms')};
  if(P.TraceRoute)o.TraceRoute=h.ext?['192.168.10.1','80.10.236.1','193.252.101.86','0.0.0.0','72.14.211.26','142.250.234.41',h.ip]:[h.ip];
  return mk('TestNetConnectionResult',o);},{alias:['tnc']});
function dnsRec(name,type,val,ttl,section){const o={Name:name,Type:type,TTL:ttl||1200,Section:section||'Answer'};if(type==='A'||type==='AAAA')o.IPAddress=val;else if(type==='MX'){o.NameExchange=val;o.Preference=0;}else if(type==='CNAME')o.NameHost=val;else if(type==='SRV'){o.NameTarget=val;o.Priority=0;o.Weight=100;o.Port=389;}else o.Strings=val;return mk('Microsoft.DnsClient.Commands.DnsRecord',o);}
def('Resolve-DnsName',MODS.dns,'Name:p0 Type:p1 Server DnsOnly:sw NoHostsFile:sw CacheOnly:sw',(P,inp,ctx)=>{
  const name=toStr(P.Name);const type=(P.Type!=null?toStr(P.Type):'A_AAAA').toUpperCase();
  if(!st.ipOk)throw psErr(`${name} : Ce délai d’attente de l’opération a expiré`,'OperationTimeout','ERROR_TIMEOUT,Microsoft.DnsClient.Commands.ResolveDnsName');
  if(type==='MX'){const d=lc(name);if(MX[d])return dnsRec(name,'MX',MX[d],3600);throw notFound(`${name} : Nom DNS inexistant`,'DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName','ResourceUnavailable');}
  if(type==='SRV'){if(/_ldap\._tcp\.dc\._msdcs\.contoso\.local/i.test(name))return[dnsRec(name,'SRV','srv-ad01.contoso.local',600),dnsRec(name,'SRV','srv-ad02.contoso.local',600),dnsRec('srv-ad01.contoso.local','A','192.168.10.5',1200,'Additional'),dnsRec('srv-ad02.contoso.local','A','192.168.10.6',1200,'Additional')];throw notFound(`${name} : Nom DNS inexistant`,'DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName','ResourceUnavailable');}
  if(type==='PTR'||isIp(name)){const h=findHost(name);if(h&&!h.ext)return mk('Microsoft.DnsClient.Commands.DnsRecord_PTR',{Name:name.split('.').reverse().join('.')+'.in-addr.arpa',Type:'PTR',TTL:1200,Section:'Answer',NameHost:fqdnOf(h)});throw notFound(`${name} : Nom DNS inexistant`,'DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName','ResourceUnavailable');}
  const h=findHost(name);if(!h||h.n==='localhost'&&false)throw notFound(`${name} : Nom DNS inexistant`,'DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName','ResourceUnavailable');
  const fq=h.ext?h.n:fqdnOf(h);const r_=[];if(h.ext&&type!=='A')r_.push(dnsRec(fq,'AAAA','2a00:1450:4007:80c::200e',300));if(type!=='AAAA')r_.push(dnsRec(fq,'A',h.ip,h.ext?300:1200));return r_;});
VIEWS['Microsoft.DnsClient.Commands.DnsRecord_PTR']={t:[['Name','Name'],['Type','Type'],['TTL','TTL',1],['Section','Section'],['NameHost','NameHost']]};
def('Get-NetIPAddress',MODS.net,'IPAddress:p0 AddressFamily InterfaceAlias InterfaceIndex',(P)=>{const list=[['192.168.10.42','Ethernet',12,'IPv4',24,'Dhcp'],['127.0.0.1','Loopback Pseudo-Interface 1',1,'IPv4',8,'WellKnown'],['fe80::4c1a:9b2e:7d3f:21a5%12','Ethernet',12,'IPv6',64,'WellKnown'],['::1','Loopback Pseudo-Interface 1',1,'IPv6',128,'WellKnown']].filter(x=>st.ipOk||x[0]!=='192.168.10.42');
  return list.filter(x=>(!P.AddressFamily||lc(toStr(P.AddressFamily))===lc(x[3]))&&nameMatch(x[1],strs(P.InterfaceAlias))&&nameMatch(x[0],strs(P.IPAddress))).map(x=>mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/MSFT_NetIPAddress',{IPAddress:x[0],InterfaceIndex:x[2],InterfaceAlias:x[1],AddressFamily:x[3],Type:'Unicast',PrefixLength:x[4],PrefixOrigin:x[5],SuffixOrigin:x[5]==='Dhcp'?'Dhcp':'WellKnown',AddressState:'Preferred',ValidLifetime:x[5]==='Dhcp'?'7.20:28:11':'Infinite ([TimeSpan]::MaxValue)',PreferredLifetime:x[5]==='Dhcp'?'7.20:28:11':'Infinite ([TimeSpan]::MaxValue)',SkipAsSource:false,PolicyStore:'ActiveStore'},{__s:x[0]}));});
def('Get-NetIPConfiguration',MODS.net,'InterfaceAlias:p0 Detailed:sw All:sw',(P)=>{const o=mk('NetIPConfiguration',{InterfaceAlias:'Ethernet',InterfaceIndex:12,InterfaceDescription:'Intel(R) Ethernet Connection (17) I219-LM','NetProfile.Name':'contoso.local',IPv4Address:st.ipOk?ME.ip:'',IPv6DefaultGateway:'',IPv4DefaultGateway:st.ipOk?ME.gw:'',DNSServer:st.ipOk?ME.dns:['fec0:0:0:ffff::1%1']},{__lines:function(){const ks=Object.keys(this);const w=Math.max(...ks.map(k=>k.length));const out=[''];ks.forEach(k=>{const v=this[k];const vs=Array.isArray(v)?v:[v];out.push(`${k.padEnd(w)} : ${vs[0]==null?'':vs[0]}`);vs.slice(1).forEach(x=>out.push(' '.repeat(w+3)+x));});out.push('');return out;}});if(P.Detailed){o.NetAdapter_Status='Up';o.MacAddress=ME.mac;o.NetIPv4Interface_Dhcp='Enabled';}return o;},{alias:['gip']});
def('Get-NetAdapter',MODS.adapter,'Name:p0 Physical:sw',(P)=>[['Ethernet','Intel(R) Ethernet Connection (17) I219-LM',12,st.ipOk?'Up':'Up',ME.mac,'1 Gbps'],['Wi-Fi','Intel(R) Wi-Fi 6E AX211 160MHz',7,'Disconnected','70-A8-D3-11-42-9B','0 bps']].filter(a=>nameMatch(a[0],strs(P.Name))).map(a=>mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/MSFT_NetAdapter',{Name:a[0],InterfaceDescription:a[1],ifIndex:a[2],Status:a[3],MacAddress:a[4],LinkSpeed:a[5]},{__s:a[0]})));
def('Restart-NetAdapter',MODS.adapter,'Name:p0',(P)=>{host(L(`(Simulation) La carte ${toStr(P.Name||'Ethernet')} est désactivée puis réactivée.`,'t-warn'));return[];});
def('Disable-NetAdapter',MODS.adapter,'Name:p0 Confirm:sw',(P)=>{host(L(`(Simulation) Carte ${toStr(P.Name)} désactivée. Attention à ne pas couper ta propre connexion à distance !`,'t-warn'));return[];});
def('Enable-NetAdapter',MODS.adapter,'Name:p0',()=>[]);
def('Get-NetTCPConnection',MODS.net,'LocalAddress LocalPort RemoteAddress RemotePort State OwningProcess',(P)=>CONNS.filter(c=>c[0]==='TCP').map(c=>{const [la,lp]=c[1].split(':'),[ra,rp]=c[2].split(':');return mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/MSFT_NetTCPConnection',{LocalAddress:la,LocalPort:+lp,RemoteAddress:ra,RemotePort:+rp,State:{LISTENING:'Listen',ESTABLISHED:'Established',TIME_WAIT:'TimeWait'}[c[3]],AppliedSetting:c[3]==='LISTENING'?'':'Internet',OwningProcess:c[4],CreationTime:ago(0,8,c[4]%60)});})
  .filter(o=>(P.State==null||strs(P.State).some(s=>lc(s)===lc(o.State)))&&(P.LocalPort==null||arr(P.LocalPort).map(toNum).includes(o.LocalPort))&&(P.RemotePort==null||arr(P.RemotePort).map(toNum).includes(o.RemotePort))&&(P.OwningProcess==null||arr(P.OwningProcess).map(toNum).includes(o.OwningProcess))&&(P.RemoteAddress==null||strs(P.RemoteAddress).includes(o.RemoteAddress))));
def('Get-DnsClientServerAddress',MODS.dns,'InterfaceAlias:p0 AddressFamily',(P)=>[['Ethernet',12,'IPv4',ME.dns],['Ethernet',12,'IPv6',[]],['Wi-Fi',7,'IPv4',[]]].filter(x=>nameMatch(x[0],strs(P.InterfaceAlias))&&(!P.AddressFamily||lc(toStr(P.AddressFamily))===lc(x[2]))).map(x=>mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/MSFT_DNSClientServerAddress',{InterfaceAlias:x[0],InterfaceIndex:x[1],AddressFamily:x[2],ServerAddresses:x[3]})));
def('Set-DnsClientServerAddress',MODS.dns,'InterfaceAlias:p0 ServerAddresses ResetServerAddresses:sw',(P,inp,ctx)=>{if(ctx.whatif){ctx.wi('Set-DnsClientServerAddress',toStr(P.InterfaceAlias));return[];}if(P.ServerAddresses!=null)ME.dns=strs(P.ServerAddresses);return[];});
def('Get-DnsClientCache',MODS.dns,'Entry:p0',()=>st.dnsCache===false?[]:[['srv-fichiers.contoso.local','192.168.10.10'],['outlook.office365.com','52.97.211.162'],['srv-ad01.contoso.local','192.168.10.5']].map(x=>mk('DnsClientCache',{Entry:x[0],RecordName:x[0],Record:'A',Type:'Success',Status:'Answer',Section:'Answer',TimeToLive:1174,DataLength:4,Data:x[1]})));
def('Clear-DnsClientCache',MODS.dns,'',()=>{st.dnsCache=false;return[];});
def('Get-NetFirewallProfile',MODS.fw,'Name:p0',(P)=>['Domain','Private','Public'].filter(n=>nameMatch(n,strs(P.Name))).map(n=>mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/MSFT_NetFirewallProfile',{Name:n,Enabled:true,DefaultInboundAction:'NotConfigured',DefaultOutboundAction:'NotConfigured',LogFileName:'%systemroot%\\system32\\LogFiles\\Firewall\\pfirewall.log'})));
def('Set-NetFirewallProfile',MODS.fw,'Profile@Name:p0 Enabled',(P,inp,ctx)=>{if(P.Enabled!=null&&!truthy(P.Enabled))ctx.warn('Désactiver le pare-feu sur tous les profils expose le poste. Préfère une règle ciblée (New-NetFirewallRule).');return[];});
def('Get-NetFirewallRule',MODS.fw,'DisplayName:p0 Name Enabled Direction',(P)=>[['Bureau à distance - Mode utilisateur (TCP-Entrée)','RemoteDesktop-UserMode-In-TCP','True','Inbound','Allow'],['Partage de fichiers et d’imprimantes (SMB-Entrée)','FPS-SMB-In-TCP','True','Inbound','Allow'],['Gestion à distance de Windows (HTTP-Entrée)','WINRM-HTTP-In-TCP','False','Inbound','Allow'],['Partage de fichiers et d’imprimantes (Demande d’écho - Trafic entrant ICMPv4)','FPS-ICMP4-ERQ-In','True','Inbound','Allow']].filter(r_=>nameMatch(r_[0],strs(P.DisplayName))).map(r_=>mk('Microsoft.Management.Infrastructure.CimInstance#root/StandardCimv2/MSFT_NetFirewallRule',{Name:r_[1],DisplayName:r_[0],Enabled:r_[2],Profile:'Domain',Direction:r_[3],Action:r_[4]})));
def('New-NetFirewallRule',MODS.fw,'DisplayName:p0 Direction Protocol LocalPort RemoteAddress Action Profile Program',(P,inp,ctx)=>{if(ctx.whatif){ctx.wi('New-NetFirewallRule',toStr(P.DisplayName));return[];}return mk('Microsoft.Management.Infrastructure.CimInstance#root/StandardCimv2/MSFT_NetFirewallRule',{Name:'{'+guid(toStr(P.DisplayName))+'}',DisplayName:toStr(P.DisplayName),Enabled:'True',Profile:P.Profile!=null?toStr(P.Profile):'Any',Direction:P.Direction!=null?toStr(P.Direction):'Inbound',Action:P.Action!=null?toStr(P.Action):'Allow',Status:'La règle a été analysée correctement à partir de la banque.'});});
def('Get-SmbShare',MODS.smb,'Name:p0',(P)=>[['ADMIN$','*','C:\\Windows','Administration à distance'],['C$','*','C:\\','Partage par défaut'],['D$','*','D:\\','Partage par défaut'],['IPC$','*','','IPC distant']].filter(s=>nameMatch(s[0],strs(P.Name))).map(s=>mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/Microsoft/Windows/SMB/MSFT_SmbShare',{Name:s[0],ScopeName:s[1],Path:s[2],Description:s[3]})));
VIEWS['Microsoft.Management.Infrastructure.CimInstance#ROOT/Microsoft/Windows/SMB/MSFT_SmbShare']={t:[['Name','Name'],['ScopeName','ScopeName'],['Path','Path'],['Description','Description']]};
def('Get-SmbMapping',MODS.smb,'LocalPath:p0',()=>Object.keys(st.mapped).map(k=>mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/Microsoft/Windows/SMB/MSFT_SmbMapping',{Status:'OK',LocalPath:k+':',RemotePath:st.mapped[k].unc})));
def('New-SmbMapping',MODS.smb,'LocalPath:p0 RemotePath:p1 Persistent',(P,inp,ctx)=>{const r_={out:[],err:[],res:{}};const code=CMD.net(['use',toStr(P.LocalPath),toStr(P.RemotePath)],r_);if(code)throw psErr(r_.err.join(' ')||'Le chemin réseau n’a pas été trouvé.','InvalidOperation','Windows System Error 53,New-SmbMapping');return mk('Microsoft.Management.Infrastructure.CimInstance#ROOT/Microsoft/Windows/SMB/MSFT_SmbMapping',{Status:'OK',LocalPath:toStr(P.LocalPath),RemotePath:toStr(P.RemotePath)});});
def('Get-SmbSession',MODS.smb,'',()=>[mk('SmbSession',{SessionId:'687194767437',ClientComputerName:'192.168.10.61',ClientUserName:'CONTOSO\\jrobert',NumOpens:3})]);
