
/* =========================================================
   Cmdlets : Active Directory
   ========================================================= */
const AD_DEF_USER=['DistinguishedName','Enabled','GivenName','Name','ObjectClass','ObjectGUID','SamAccountName','SID','Surname','UserPrincipalName'];
const AD_EXTRA_USER=['AccountExpirationDate','BadLogonCount','CannotChangePassword','CanonicalName','City','Company','Created','Department','Description','DisplayName','EmailAddress','HomeDirectory','LastBadPasswordAttempt','LastLogonDate','LockedOut','logonCount','mail','Manager','MemberOf','Modified','Office','OfficePhone','PasswordExpired','PasswordLastSet','PasswordNeverExpires','telephoneNumber','Title','whenChanged','whenCreated'];
function canon(dn){const parts=dn.split(/,(?=(?:OU|CN|DC)=)/);const dc=parts.filter(p=>/^DC=/.test(p)).map(p=>p.slice(3)).join('.');const rest=parts.filter(p=>!/^DC=/.test(p)).map(p=>p.replace(/^(OU|CN)=/,'')).reverse();return dc+'/'+rest.join('/');}
function userAttr(u,k){switch(lc(k)){case'created':case'whencreated':return u.whenCreated;case'modified':case'whenchanged':return ago(1);case'mail':return u.EmailAddress;case'officephone':case'telephonenumber':return u.telephoneNumber;case'canonicalname':return canon(u.DistinguishedName);case'cannotchangepassword':return false;case'city':return 'Nice';case'logoncount':return u.logonCount;}const kk=Object.keys(u).find(x=>lc(x)===lc(k));return kk?u[kk]:undefined;}
function adUserObj(u,props){
  const want=new Set(AD_DEF_USER);
  const ps=strs(props);if(ps.includes('*'))AD_EXTRA_USER.forEach(k=>want.add(k));else ps.forEach(p=>{const k=AD_EXTRA_USER.find(x=>lc(x)===lc(p))||p;want.add(k);});
  const o={};[...want].sort((a,b)=>lc(a)<lc(b)?-1:lc(a)>lc(b)?1:0).forEach(k=>{const v=userAttr(u,k);o[k]=v===undefined?null:(Array.isArray(v)?v.slice():v);});
  return mk('Microsoft.ActiveDirectory.Management.ADUser',o,{__s:u.DistinguishedName,__ad:u,__lines:null});
}
const AD_DEF_COMP=['DistinguishedName','DNSHostName','Enabled','Name','ObjectClass','ObjectGUID','SamAccountName','SID','UserPrincipalName'];
const AD_EXTRA_COMP=['CanonicalName','Created','Description','IPv4Address','LastLogonDate','OperatingSystem','OperatingSystemVersion','PasswordLastSet','whenCreated'];
function compAttr(c,k){switch(lc(k)){case'created':case'whencreated':return c.whenCreated;case'canonicalname':return canon(c.DistinguishedName);case'passwordlastset':return c.LastLogonDate?new Date(c.LastLogonDate.getTime()-5*864e5):null;}const kk=Object.keys(c).find(x=>lc(x)===lc(k));return kk?c[kk]:undefined;}
function adCompObj(c,props){const want=new Set(AD_DEF_COMP);const ps=strs(props);if(ps.includes('*'))AD_EXTRA_COMP.forEach(k=>want.add(k));else ps.forEach(p=>want.add(AD_EXTRA_COMP.find(x=>lc(x)===lc(p))||p));const o={};[...want].sort((a,b)=>lc(a)<lc(b)?-1:lc(a)>lc(b)?1:0).forEach(k=>{const v=compAttr(c,k);o[k]=v===undefined?null:v;});return mk('Microsoft.ActiveDirectory.Management.ADComputer',o,{__s:c.DistinguishedName,__ad:c});}
function adGroupObj(g,props){const o={DistinguishedName:g.DistinguishedName,GroupCategory:g.GroupCategory,GroupScope:g.GroupScope,Name:g.Name,ObjectClass:'group',ObjectGUID:g.ObjectGUID,SamAccountName:g.SamAccountName,SID:g.SID};const ps=strs(props);if(ps.includes('*')||ps.some(p=>lc(p)==='description'))o.Description=g.Description;if(ps.includes('*')||ps.some(p=>lc(p)==='members'))o.Members=g.members.map(m=>{const u=adUser(m);const gg=adGroup(m);return u?u.DistinguishedName:gg?gg.DistinguishedName:'CN='+m+',CN=Users,'+DOM.dn;});if(ps.includes('*')||ps.some(p=>lc(p)==='memberof'))o.MemberOf=AD.groups.filter(x=>x.members.some(m=>lc(m)===lc(g.Name))).map(x=>x.DistinguishedName);
  const s={};Object.keys(o).sort((a,b)=>lc(a)<lc(b)?-1:1).forEach(k=>s[k]=o[k]);return mk('Microsoft.ActiveDirectory.Management.ADGroup',s,{__s:g.DistinguishedName,__ad:g});}
const ADNF=(id,kind)=>{const e=psErr(`Impossible de trouver un objet avec l’identité « ${id} » sous : « ${DOM.dn} ».`,'ObjectNotFound',`ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException,Microsoft.ActiveDirectory.Management.Commands.${kind}`);e.target=`${id}:AD${/Computer/.test(kind)?'Computer':/Group/.test(kind)?'Group':'User'}`;return e;};
function idOf(v){if(isObj(v)){return toStr(getMember(v,'SamAccountName')||getMember(v,'DistinguishedName')||getMember(v,'Name'));}return toStr(v);}
function findUserId(id,kind){const s=lc(idOf(id));const u=AD.users.find(x=>lc(x.SamAccountName)===s||lc(x.DistinguishedName)===s||lc(x.SID)===s||lc(x.ObjectGUID)===s);if(!u){const e=ADNF(idOf(id),kind||'GetADUser');if(AD.users.some(x=>lc(x.Name)===s||lc(x.UserPrincipalName)===s))e.hint='(-Identity accepte le SamAccountName, le DN, le SID ou le GUID — pas le nom complet ni l’UPN. Ex. : Get-ADUser -Filter "Name -eq \''+idOf(id)+'\'")';throw e;}return u;}
function findCompId(id,kind){const s=lc(idOf(id)).replace(/\$$/,'');const c=AD.computers.find(x=>lc(x.Name)===s||lc(x.DistinguishedName)===s||lc(x.SID)===s);if(!c)throw ADNF(idOf(id),kind||'GetADComputer');return c;}
function findGroupId(id,kind){const s=lc(idOf(id));const g=AD.groups.find(x=>lc(x.SamAccountName)===s||lc(x.Name)===s||lc(x.DistinguishedName)===s||lc(x.SID)===s);if(!g)throw ADNF(idOf(id),kind||'GetADGroup');return g;}
function findPrincipal(id){const s=lc(idOf(id));return AD.users.find(x=>lc(x.SamAccountName)===s||lc(x.DistinguishedName)===s)||AD.groups.find(x=>lc(x.SamAccountName)===s||lc(x.DistinguishedName)===s)||AD.computers.find(x=>lc(x.SamAccountName)===s||lc(x.Name)===s||lc(x.DistinguishedName)===s);}
function needId(P,kind){if(P.Identity==null&&P.Filter==null&&P.LDAPFilter==null)throw psErr('Le simulateur ne peut pas demander de saisie : précise -Identity <SamAccountName> ou -Filter "...".','InvalidArgument','MissingMandatoryParameter,Microsoft.ActiveDirectory.Management.Commands.'+kind);}
function ldapToFilter(f){const m=/^\(?\s*\(?(\w+)\s*=\s*([^)]*)\)?\s*\)?$/.exec(toStr(f).trim());if(!m)throw psErr('Le simulateur ne gère que des filtres LDAP simples, ex. (sAMAccountName=jdupont).','InvalidArgument','LDAPFilterNotSupported');const k={samaccountname:'SamAccountName',department:'Department',title:'Title',mail:'EmailAddress',cn:'Name',name:'Name',givenname:'GivenName',sn:'Surname'}[lc(m[1])]||m[1];return `${k} -like '${m[2]}'`;}
function searchBase(list,P){if(P.SearchBase==null)return list;const sb=lc(toStr(P.SearchBase));const scope=lc(toStr(P.SearchScope||'Subtree'));if(!AD.ous.some(o=>lc(o)===sb)&&!/^cn=users,|^dc=/.test(sb))throw psErr('Objet directory introuvable','ObjectNotFound','ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException');return list.filter(x=>{const dn=lc(x.DistinguishedName);if(scope==='onelevel')return dn.replace(/^[^,]+,/,'')===sb;return dn.endsWith(','+sb)||dn===sb;});}
def('Get-ADUser',MODS.ad,'Identity:p0 Filter LDAPFilter Properties@Property SearchBase SearchScope ResultSetSize Server Credential',(P,inp,ctx)=>{
  if(P.Identity==null&&inp.length&&P.Filter==null)return inp.map(i=>adUserObj(findUserId(i),P.Properties));
  needId(P,'GetADUser');
  if(P.Identity!=null)return arr(P.Identity).map(i=>adUserObj(findUserId(i),P.Properties));
  let list=searchBase(AD.users,P);
  const f=P.LDAPFilter!=null?ldapToFilter(P.LDAPFilter):P.Filter;
  list=filterObjs(list.map(u=>Object.assign(Object.create(null),u,{mail:u.EmailAddress,Created:u.whenCreated,OfficePhone:u.telephoneNumber,__u:u})),f,ctx.scope).map(x=>x.__u);
  if(P.ResultSetSize!=null)list=list.slice(0,toNum(P.ResultSetSize));
  return list.map(u=>adUserObj(u,P.Properties));
});
function applyUserSet(u,P){
  const map={GivenName:'GivenName',Surname:'Surname',DisplayName:'DisplayName',Title:'Title',Department:'Department',Office:'Office',Company:'Company',Description:'Description',EmailAddress:'EmailAddress',OfficePhone:'telephoneNumber',HomeDirectory:'HomeDirectory',Manager:'Manager'};
  Object.keys(map).forEach(k=>{if(P[k]!==undefined){u[map[k]]=P[k]==null?null:(k==='Manager'?findUserId(P[k],'SetADUser').DistinguishedName:toStr(P[k]));}});
  if(P.Enabled!==undefined)u.Enabled=truthy(P.Enabled);
  if(P.PasswordNeverExpires!==undefined)u.PasswordNeverExpires=truthy(P.PasswordNeverExpires);
  if(P.ChangePasswordAtLogon!==undefined){if(truthy(P.ChangePasswordAtLogon)){if(u.PasswordNeverExpires)throw psErr('Impossible de définir « Le mot de passe n’expire jamais » et « L’utilisateur doit changer le mot de passe à la prochaine ouverture de session » en même temps.','InvalidOperation','ActiveDirectoryServer:0,Microsoft.ActiveDirectory.Management.Commands.SetADUser');u.PasswordLastSet=null;u.PasswordExpired=true;}else{u.PasswordLastSet=u.PasswordLastSet||new Date();u.PasswordExpired=false;}}
  if(P.Replace!=null&&isHt(P.Replace))Object.keys(P.Replace).forEach(k=>{const kk=Object.keys(u).find(x=>lc(x)===lc(k))||k;u[kk]=P.Replace[k];});
  if(P.Clear!=null)strs(P.Clear).forEach(k=>{const kk=Object.keys(u).find(x=>lc(x)===lc(k));if(kk)u[kk]=null;});
}
def('Set-ADUser',MODS.ad,'Identity:p0 GivenName Surname DisplayName Title Department Office Company Description EmailAddress OfficePhone HomeDirectory HomeDrive ScriptPath Manager Enabled ChangePasswordAtLogon PasswordNeverExpires Replace Add Clear PassThru:sw Server',(P,inp,ctx)=>{
  const ids=P.Identity!=null?arr(P.Identity):inp;if(!ids.length)needId(P,'SetADUser');const out=[];
  ids.forEach(i=>{const u=findUserId(i,'SetADUser');if(ctx.whatif){ctx.wi('Set',u.DistinguishedName);return;}applyUserSet(u,P);if(P.PassThru)out.push(adUserObj(u));});return out;});
def('New-ADUser',MODS.ad,'Name:p0 SamAccountName GivenName Surname DisplayName UserPrincipalName Path AccountPassword Enabled ChangePasswordAtLogon PasswordNeverExpires Department Title EmailAddress Description Office OfficePhone Company HomeDirectory HomeDrive Manager OtherAttributes PassThru:sw Server Instance',(P,inp,ctx)=>{
  if(P.Name==null)throw psErr('Le paramètre Name est obligatoire (le simulateur ne peut pas le demander).','InvalidArgument','MissingMandatoryParameter');
  const name=toStr(P.Name);const sam=P.SamAccountName!=null?toStr(P.SamAccountName):name;
  if(sam.length>20)throw psErr('Le nom d’ouverture de session antérieur à Windows 2000 (SamAccountName) ne peut pas dépasser 20 caractères.','InvalidArgument','ActiveDirectoryServer:8312');
  const path=P.Path!=null?toStr(P.Path):'CN=Users,'+DOM.dn;
  if(!AD.ous.some(o=>lc(o)===lc(path))&&lc(path)!==lc('CN=Users,'+DOM.dn)){const e=psErr('Objet directory introuvable','ObjectNotFound','ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException,Microsoft.ActiveDirectory.Management.Commands.NewADUser');e.target=`CN=${name},${path}:String`;throw e;}
  if(AD.users.some(u=>lc(u.SamAccountName)===lc(sam))||AD.users.some(u=>lc(u.DistinguishedName)===lc(`CN=${name},${path}`))){const e=psErr('Le compte spécifié existe déjà','ResourceExists','ActiveDirectoryServer:1316,Microsoft.ActiveDirectory.Management.Commands.NewADUser');e.target=`CN=${name},${path}:String`;throw e;}
  if(P.AccountPassword!=null&&typeof P.AccountPassword==='string')throw psErr(`Impossible de lier le paramètre « AccountPassword ». Impossible de convertir la valeur « ${P.AccountPassword} » du type « System.String » en type « System.Security.SecureString ».`,'InvalidArgument','CannotConvertArgumentNoMessage,Microsoft.ActiveDirectory.Management.Commands.NewADUser');
  const en=P.Enabled!=null?truthy(P.Enabled):false;
  if(en&&P.AccountPassword==null)throw psErr('Impossible de mettre à jour le mot de passe. La valeur fournie pour le nouveau mot de passe ne respecte pas les exigences de longueur, de complexité ou d’historique du domaine.','InvalidData','ActiveDirectoryServer:1325,Microsoft.ActiveDirectory.Management.Commands.NewADUser');
  if(ctx.whatif){ctx.wi('New',`CN=${name},${path}`);return[];}
  const u={SamAccountName:sam,GivenName:P.GivenName!=null?toStr(P.GivenName):null,Surname:P.Surname!=null?toStr(P.Surname):null,Name:name,DisplayName:P.DisplayName!=null?toStr(P.DisplayName):null,UserPrincipalName:P.UserPrincipalName!=null?toStr(P.UserPrincipalName):null,EmailAddress:P.EmailAddress!=null?toStr(P.EmailAddress):null,Department:null,Title:null,Company:null,Office:null,telephoneNumber:null,Description:null,Enabled:en,LockedOut:false,PasswordExpired:false,PasswordNeverExpires:false,PasswordLastSet:P.AccountPassword!=null?new Date():null,LastLogonDate:null,BadLogonCount:0,LastBadPasswordAttempt:null,whenCreated:new Date(),AccountExpirationDate:null,logonCount:0,HomeDirectory:null,MemberOf:[],Manager:null,DistinguishedName:`CN=${name},${path}`,ObjectClass:'user',ObjectGUID:guid(sam),SID:`${DOM.sid}-${1200+AD.users.length}`};
  applyUserSet(u,Object.assign({},P,{Enabled:undefined,ChangePasswordAtLogon:P.ChangePasswordAtLogon,GivenName:undefined,Surname:undefined,DisplayName:undefined,EmailAddress:undefined}));
  AD.users.push(u);AD.groups.find(g=>g.Name==='Utilisateurs du domaine').members.push(sam);
  return P.PassThru?adUserObj(u):[];
});
def('Remove-ADUser',MODS.ad,'Identity:p0 Confirm:sw',(P,inp,ctx)=>{(P.Identity!=null?arr(P.Identity):inp).forEach(i=>{const u=findUserId(i,'RemoveADUser');if(ctx.whatif){ctx.wi('Remove',u.DistinguishedName);return;}if(P.Confirm!==false){host(L('Confirmer'));host(L(`Voulez-vous vraiment effectuer cette action ?`));host(L(`Opération « Remove » en cours sur la cible « ${u.DistinguishedName} ».`));host(L('[O] Oui  [T] Oui pour tout  [N] Non  [U] Non pour tout  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») : O'));}AD.users.splice(AD.users.indexOf(u),1);AD.groups.forEach(g=>g.members=g.members.filter(m=>lc(m)!==lc(u.SamAccountName)));});return[];});
function acctTarget(i,kind){if(isObj(i)&&lc(toStr(getMember(i,'ObjectClass')))==='computer')return findCompId(i,kind);const s=lc(idOf(i));if(/\$$/.test(s)||AD.computers.some(c=>lc(c.Name)===s&&!AD.users.some(u=>lc(u.SamAccountName)===s)))return findCompId(i,kind);return findUserId(i,kind);}
def('Unlock-ADAccount',MODS.ad,'Identity:p0 PassThru:sw Server',(P,inp,ctx)=>{const ids=P.Identity!=null?arr(P.Identity):inp;if(!ids.length)needId(P,'UnlockADAccount');const out=[];ids.forEach(i=>{const u=findUserId(i,'UnlockADAccount');if(ctx.whatif){ctx.wi('Unlock',u.DistinguishedName);return;}u.LockedOut=false;u.BadLogonCount=0;if(P.PassThru)out.push(adUserObj(u));});return out;});
def('Enable-ADAccount',MODS.ad,'Identity:p0 PassThru:sw',(P,inp,ctx)=>{const ids=P.Identity!=null?arr(P.Identity):inp;ids.forEach(i=>{const a=acctTarget(i,'EnableADAccount');if(ctx.whatif){ctx.wi('Enable',a.DistinguishedName);return;}if(a.ObjectClass==='user'&&!a.PasswordLastSet)throw psErr('Impossible de mettre à jour le mot de passe. La valeur fournie pour le nouveau mot de passe ne respecte pas les exigences de longueur, de complexité ou d’historique du domaine.','InvalidData','ActiveDirectoryServer:1325,Microsoft.ActiveDirectory.Management.Commands.EnableADAccount');a.Enabled=true;});return[];});
def('Disable-ADAccount',MODS.ad,'Identity:p0 PassThru:sw',(P,inp,ctx)=>{const ids=P.Identity!=null?arr(P.Identity):inp;ids.forEach(i=>{const a=acctTarget(i,'DisableADAccount');if(ctx.whatif){ctx.wi('Set',a.DistinguishedName);return;}a.Enabled=false;});return[];});
def('Set-ADAccountPassword',MODS.ad,'Identity:p0 NewPassword OldPassword Reset:sw PassThru:sw Server',(P,inp,ctx)=>{const ids=P.Identity!=null?arr(P.Identity):inp;if(!ids.length)needId(P,'SetADAccountPassword');
  if(P.NewPassword==null)throw psErr('Le simulateur ne peut pas demander le mot de passe : passe -NewPassword (Read-Host -AsSecureString "Nouveau mot de passe").','InvalidArgument','MissingMandatoryParameter');
  if(typeof P.NewPassword==='string')throw psErr(`Impossible de lier le paramètre « NewPassword ». Impossible de convertir la valeur « ${P.NewPassword} » du type « System.String » en type « System.Security.SecureString ».`,'InvalidArgument','CannotConvertArgumentNoMessage,Microsoft.ActiveDirectory.Management.Commands.SetADAccountPassword');
  if(!P.Reset&&P.OldPassword==null)throw psErr('Sans -Reset, il faut fournir -OldPassword (changement par l’utilisateur). En support, on utilise -Reset.','InvalidArgument','MissingOldPassword');
  ids.forEach(i=>{const u=findUserId(i,'SetADAccountPassword');if(ctx.whatif){ctx.wi('Set-ADAccountPassword',u.DistinguishedName);return;}u.PasswordLastSet=new Date();u.PasswordExpired=false;});return[];});
function tsDays(v){if(v==null)return 15;if(isObj(v)&&v.__ts!=null)return v.__ts/864e5;if(typeof v==='number')return v;const s=toStr(v);const m=/^(\d+)(?:\.(\d+):(\d+):(\d+))?$/.exec(s);if(m)return +m[1]+(m[2]?(+m[2])/24:0);return toNum(s);}
function acctObj(a){const o={AccountExpirationDate:a.AccountExpirationDate||null,DistinguishedName:a.DistinguishedName,Enabled:a.Enabled,LastLogonDate:a.LastLogonDate||null,LockedOut:!!a.LockedOut,Name:a.Name,ObjectClass:a.ObjectClass,ObjectGUID:a.ObjectGUID,PasswordExpired:!!a.PasswordExpired,PasswordNeverExpires:!!a.PasswordNeverExpires,SamAccountName:a.SamAccountName,SID:a.SID,UserPrincipalName:a.UserPrincipalName||null};return mk(a.ObjectClass==='computer'?'Microsoft.ActiveDirectory.Management.ADComputer':'Microsoft.ActiveDirectory.Management.ADUser',o,{__s:a.DistinguishedName,__ad:a});}
def('Search-ADAccount',MODS.ad,'LockedOut:sw AccountDisabled:sw AccountInactive:sw AccountExpired:sw AccountExpiring:sw PasswordExpired:sw PasswordNeverExpires:sw TimeSpan DateTime UsersOnly:sw ComputersOnly:sw SearchBase ResultSetSize',(P,inp,ctx)=>{
  let list=[];if(!P.ComputersOnly)list=list.concat(AD.users);if(!P.UsersOnly)list=list.concat(AD.computers.map(c=>Object.assign(c,{LockedOut:false,PasswordExpired:false,PasswordNeverExpires:false})));
  list=searchBase(list,P);
  if(!(P.LockedOut||P.AccountDisabled||P.AccountInactive||P.AccountExpired||P.AccountExpiring||P.PasswordExpired||P.PasswordNeverExpires))throw psErr('Le jeu de paramètres ne peut pas être résolu : précise un critère (-LockedOut, -AccountDisabled, -AccountInactive, -PasswordExpired…).','InvalidArgument','AmbiguousParameterSet,Microsoft.ActiveDirectory.Management.Commands.SearchADAccount');
  if(P.LockedOut)list=list.filter(a=>a.LockedOut);
  if(P.AccountDisabled)list=list.filter(a=>!a.Enabled);
  if(P.PasswordExpired)list=list.filter(a=>a.PasswordExpired);
  if(P.PasswordNeverExpires)list=list.filter(a=>a.PasswordNeverExpires);
  if(P.AccountExpired)list=list.filter(a=>a.AccountExpirationDate&&a.AccountExpirationDate<new Date());
  if(P.AccountExpiring)list=list.filter(a=>a.AccountExpirationDate&&a.AccountExpirationDate>new Date());
  if(P.AccountInactive){const lim=P.DateTime!=null?toDate(P.DateTime):new Date(Date.now()-tsDays(P.TimeSpan)*864e5);list=list.filter(a=>!a.LastLogonDate||a.LastLogonDate<lim);}
  return list.map(acctObj);
});
def('Get-ADGroup',MODS.ad,'Identity:p0 Filter LDAPFilter Properties SearchBase',(P,inp,ctx)=>{needId(P,'GetADGroup');if(P.Identity!=null)return arr(P.Identity).map(i=>adGroupObj(findGroupId(i),P.Properties));let list=searchBase(AD.groups,P);list=filterObjs(list.map(g=>Object.assign(Object.create(null),g,{__g:g})),P.LDAPFilter!=null?ldapToFilter(P.LDAPFilter):P.Filter,ctx.scope).map(x=>x.__g);return list.map(g=>adGroupObj(g,P.Properties));});
function memberObj(m){const u=adUser(m);if(u)return mk('Microsoft.ActiveDirectory.Management.ADPrincipal',{distinguishedName:u.DistinguishedName,name:u.Name,objectClass:'user',objectGUID:u.ObjectGUID,SamAccountName:u.SamAccountName,SID:u.SID},{__s:u.DistinguishedName});const g=adGroup(m);if(g)return mk('Microsoft.ActiveDirectory.Management.ADPrincipal',{distinguishedName:g.DistinguishedName,name:g.Name,objectClass:'group',objectGUID:g.ObjectGUID,SamAccountName:g.SamAccountName,SID:g.SID},{__s:g.DistinguishedName});
  const c=/\$$/.test(m)?adComputer(m):null;if(c)return mk('Microsoft.ActiveDirectory.Management.ADPrincipal',{distinguishedName:c.DistinguishedName,name:c.Name,objectClass:'computer',objectGUID:c.ObjectGUID||guid(c.Name),SamAccountName:c.Name+'$',SID:c.SID||(DOM.sid+'-'+(2000+(hash32(c.Name)%900)))},{__s:c.DistinguishedName});
  return mk('Microsoft.ActiveDirectory.Management.ADPrincipal',{distinguishedName:`CN=${m},CN=Users,${DOM.dn}`,name:m,objectClass:'user',objectGUID:guid(m),SamAccountName:m,SID:DOM.sid+'-500'},{__s:m});}
def('Get-ADGroupMember',MODS.ad,'Identity:p0 Recursive:sw Server',(P,inp,ctx)=>{const ids=P.Identity!=null?arr(P.Identity):inp;if(!ids.length)needId(P,'GetADGroupMember');const out=[];const seen=new Set();
  const walk=g=>{g.members.forEach(m=>{const sub=adGroup(m);if(sub&&P.Recursive){walk(sub);return;}if(seen.has(lc(m)))return;seen.add(lc(m));out.push(memberObj(m));});};
  ids.forEach(i=>walk(findGroupId(i,'GetADGroupMember')));return out;});
def('Add-ADGroupMember',MODS.ad,'Identity:p0 Members:p1 PassThru:sw',(P,inp,ctx)=>{const g=findGroupId(P.Identity!=null?P.Identity:inp[0],'AddADGroupMember');const ms=P.Members!=null?arr(P.Members):[];if(!ms.length)throw psErr('Le paramètre Members est obligatoire.','InvalidArgument','MissingMandatoryParameter');
  ms.forEach(m=>{const pr=findPrincipal(m);if(!pr)throw ADNF(idOf(m),'AddADGroupMember');const sam=pr.ObjectClass==='group'?pr.Name:pr.SamAccountName;if(g.members.some(x=>lc(x)===lc(sam)))throw psErr('Le nom de compte spécifié est déjà membre du groupe.','ResourceExists','ActiveDirectoryServer:1378,Microsoft.ActiveDirectory.Management.Commands.AddADGroupMember');if(ctx.whatif){ctx.wi('Set',g.DistinguishedName);return;}g.members.push(sam);if(pr.MemberOf)pr.MemberOf.push(g.DistinguishedName);});return[];});
def('Remove-ADGroupMember',MODS.ad,'Identity:p0 Members:p1 Confirm:sw',(P,inp,ctx)=>{const g=findGroupId(P.Identity,'RemoveADGroupMember');const ms=arr(P.Members);if(P.Confirm!==false){host(L('Confirmer'));host(L('Voulez-vous vraiment effectuer cette action ?'));host(L(`Opération « Set » en cours sur la cible « ${g.DistinguishedName} ».`));host(L('[O] Oui  [T] Oui pour tout  [N] Non  [U] Non pour tout  [S] Suspendre  [?] Aide (la valeur par défaut est « O ») : O'));}
  ms.forEach(m=>{const pr=findPrincipal(m);if(!pr)throw ADNF(idOf(m),'RemoveADGroupMember');const sam=pr.ObjectClass==='group'?pr.Name:pr.SamAccountName;g.members=g.members.filter(x=>lc(x)!==lc(sam));if(pr.MemberOf)pr.MemberOf=pr.MemberOf.filter(d=>d!==g.DistinguishedName);});return[];});
def('Get-ADPrincipalGroupMembership',MODS.ad,'Identity:p0',(P,inp)=>{const pr=findPrincipal(P.Identity!=null?P.Identity:inp[0]);if(!pr)throw ADNF(idOf(P.Identity),'GetADPrincipalGroupMembership');const nm=pr.ObjectClass==='group'?pr.Name:pr.SamAccountName;return AD.groups.filter(g=>g.members.some(m=>lc(m)===lc(nm))).map(g=>adGroupObj(g));});
def('Get-ADComputer',MODS.ad,'Identity:p0 Filter LDAPFilter Properties@Property SearchBase SearchScope ResultSetSize',(P,inp,ctx)=>{
  if(P.Identity==null&&inp.length&&P.Filter==null)return inp.map(i=>adCompObj(findCompId(i),P.Properties));
  needId(P,'GetADComputer');if(P.Identity!=null)return arr(P.Identity).map(i=>adCompObj(findCompId(i),P.Properties));
  let list=searchBase(AD.computers,P);list=filterObjs(list.map(c=>Object.assign(Object.create(null),c,{__c:c})),P.LDAPFilter!=null?ldapToFilter(P.LDAPFilter):P.Filter,ctx.scope).map(x=>x.__c);
  if(P.ResultSetSize!=null)list=list.slice(0,toNum(P.ResultSetSize));return list.map(c=>adCompObj(c,P.Properties));});
def('Set-ADComputer',MODS.ad,'Identity:p0 Description Location Enabled PassThru:sw',(P,inp,ctx)=>{(P.Identity!=null?arr(P.Identity):inp).forEach(i=>{const c=findCompId(i,'SetADComputer');if(P.Description!==undefined)c.Description=P.Description==null?null:toStr(P.Description);if(P.Enabled!==undefined)c.Enabled=truthy(P.Enabled);});return[];});
def('Get-ADOrganizationalUnit',MODS.ad,'Identity:p0 Filter Properties SearchBase',(P,inp,ctx)=>{let l=AD.ous.map(dn=>mk('Microsoft.ActiveDirectory.Management.ADOrganizationalUnit',{City:null,Country:null,DistinguishedName:dn,LinkedGroupPolicyObjects:/Postes/.test(dn)?['cn={6AC1786C-016F-11D2-945F-00C04FB984F9},cn=policies,cn=system,DC=contoso,DC=local']:[],ManagedBy:null,Name:dn.split(',')[0].replace(/^OU=/,''),ObjectClass:'organizationalUnit',ObjectGUID:guid(dn),PostalCode:null,State:null,StreetAddress:null},{__s:dn}));
  if(P.Identity!=null){const id=lc(toStr(P.Identity));l=l.filter(o=>lc(o.DistinguishedName)===id);if(!l.length)throw ADNF(toStr(P.Identity),'GetADOrganizationalUnit');return l;}needId(P,'GetADOrganizationalUnit');return filterObjs(l,P.Filter,ctx.scope);});
def('New-ADOrganizationalUnit',MODS.ad,'Name:p0 Path ProtectedFromAccidentalDeletion',(P,inp,ctx)=>{const dn=`OU=${toStr(P.Name)},${P.Path!=null?toStr(P.Path):DOM.dn}`;if(AD.ous.some(o=>lc(o)===lc(dn)))throw psErr('Une tentative d’ajout d’un objet à l’annuaire avec un nom déjà utilisé a été effectuée','ResourceExists','ActiveDirectoryServer:8305,Microsoft.ActiveDirectory.Management.Commands.NewADOrganizationalUnit');if(ctx.whatif){ctx.wi('New',dn);return[];}AD.ous.push(dn);return[];});
def('New-ADGroup',MODS.ad,'Name:p0 GroupScope:p1 GroupCategory Path Description SamAccountName PassThru:sw',(P,inp,ctx)=>{const n=toStr(P.Name);if(P.GroupScope==null)throw psErr('Le paramètre GroupScope est obligatoire (Global, DomainLocal ou Universal).','InvalidArgument','MissingMandatoryParameter');if(adGroup(n))throw psErr('Le groupe spécifié existe déjà','ResourceExists','ActiveDirectoryServer:1318');const g={Name:n,SamAccountName:P.SamAccountName!=null?toStr(P.SamAccountName):n,GroupScope:toStr(P.GroupScope),GroupCategory:P.GroupCategory!=null?toStr(P.GroupCategory):'Security',members:[],Description:P.Description!=null?toStr(P.Description):null,DistinguishedName:`CN=${n},${P.Path!=null?toStr(P.Path):'CN=Users,'+DOM.dn}`,ObjectClass:'group',ObjectGUID:guid(n),SID:DOM.sid+'-'+(1300+AD.groups.length)};if(ctx.whatif){ctx.wi('New',g.DistinguishedName);return[];}AD.groups.push(g);return P.PassThru?adGroupObj(g):[];});
def('Move-ADObject',MODS.ad,'Identity:p0 TargetPath:p1 PassThru:sw',(P,inp,ctx)=>{const ids=P.Identity!=null?arr(P.Identity):inp;const tp=toStr(P.TargetPath);if(!AD.ous.some(o=>lc(o)===lc(tp)))throw psErr('Objet directory introuvable','ObjectNotFound','ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException,Microsoft.ActiveDirectory.Management.Commands.MoveADObject');
  ids.forEach(i=>{const s=lc(isObj(i)?toStr(getMember(i,'DistinguishedName')):toStr(i));const o=AD.users.find(x=>lc(x.DistinguishedName)===s)||AD.computers.find(x=>lc(x.DistinguishedName)===s)||AD.groups.find(x=>lc(x.DistinguishedName)===s);if(!o){const e=ADNF(toStr(isObj(i)?getMember(i,'Name'):i),'MoveADObject');e.hint='(Move-ADObject attend un DistinguishedName, ou un objet passé par le pipeline : Get-ADUser x | Move-ADObject -TargetPath "OU=...")';throw e;}
    if(ctx.whatif){ctx.wi('Move',o.DistinguishedName);return;}o.DistinguishedName=o.DistinguishedName.split(',')[0]+','+tp;});return[];});
def('Get-ADDomain',MODS.ad,'Identity:p0 Server',()=>mk('Microsoft.ActiveDirectory.Management.ADDomain',{AllowedDNSSuffixes:[],ChildDomains:[],ComputersContainer:'CN=Computers,'+DOM.dn,DistinguishedName:DOM.dn,DNSRoot:DOM.dns,DomainControllersContainer:'OU=Domain Controllers,'+DOM.dn,DomainMode:'Windows2016Domain',DomainSID:DOM.sid,Forest:DOM.dns,InfrastructureMaster:'SRV-AD01.contoso.local',Name:'contoso',NetBIOSName:'CONTOSO',ObjectClass:'domainDNS',PDCEmulator:'SRV-AD01.contoso.local',ReplicaDirectoryServers:['SRV-AD01.contoso.local','SRV-AD02.contoso.local'],RIDMaster:'SRV-AD01.contoso.local',UsersContainer:'CN=Users,'+DOM.dn},{__s:DOM.dn}));
def('Get-ADForest',MODS.ad,'Identity:p0',()=>mk('Microsoft.ActiveDirectory.Management.ADForest',{Domains:[DOM.dns],DomainNamingMaster:'SRV-AD01.contoso.local',ForestMode:'Windows2016Forest',GlobalCatalogs:['SRV-AD01.contoso.local','SRV-AD02.contoso.local'],Name:DOM.dns,RootDomain:DOM.dns,SchemaMaster:'SRV-AD01.contoso.local',Sites:['Default-First-Site-Name'],UPNSuffixes:['contoso-hotels.com']}));
def('Get-ADDomainController',MODS.ad,'Identity:p0 Filter Discover:sw Service DomainName',(P)=>{const mkdc=(n,ip,roles)=>mk('Microsoft.ActiveDirectory.Management.ADDomainController',{ComputerObjectDN:`CN=${n},OU=Domain Controllers,${DOM.dn}`,Domain:DOM.dns,Enabled:true,Forest:DOM.dns,HostName:`${n}.contoso.local`,IPv4Address:ip,IsGlobalCatalog:true,IsReadOnly:false,Name:n,OperatingSystem:'Windows Server 2022 Standard',OperationMasterRoles:roles,Site:'Default-First-Site-Name'},{__s:n});
  const all=[mkdc('SRV-AD01','192.168.10.5',['SchemaMaster','DomainNamingMaster','PDCEmulator','RIDMaster','InfrastructureMaster']),mkdc('SRV-AD02','192.168.10.6',[])];
  if(P.Filter!=null)return all;if(P.Identity!=null)return all.filter(d=>lc(d.Name)===lc(toStr(P.Identity).replace(/\.contoso\.local$/i,'')));return all[0];});
def('Get-ADDefaultDomainPasswordPolicy',MODS.ad,'Identity:p0',()=>mk('Microsoft.ActiveDirectory.Management.ADDefaultDomainPasswordPolicy',{ComplexityEnabled:true,DistinguishedName:DOM.dn,LockoutDuration:'00:30:00',LockoutObservationWindow:'00:30:00',LockoutThreshold:5,MaxPasswordAge:'90.00:00:00',MinPasswordAge:'1.00:00:00',MinPasswordLength:12,PasswordHistoryCount:24,ReversibleEncryptionEnabled:false}));
def('Get-GPResultantSetOfPolicy',MODS.ad,'ReportType Path Computer User',(P)=>{writeFile(toStr(P.Path||'C:\\Temp\\rsop.html'),'<html>RSoP</html>');return[];});
def('Invoke-GPUpdate',MODS.ad,'Computer:p0 Force:sw RandomDelayInMinutes Target',(P,inp,ctx)=>{const c=P.Computer!=null?toStr(P.Computer):null;if(c&&!findHost(c).self){const e=psErr(`L’ordinateur « ${c} » n’est pas joignable par les tâches planifiées à distance (Invoke-GPUpdate utilise une tâche planifiée distante + pare-feu « Analyse de stratégie de groupe à distance »).`,'OperationStopped','HRESULT 0x800706ba');e.hint='(Alternative sans WinRM : psexec \\\\'+c+' gpupdate /force)';throw e;}host(L('(Simulation) gpupdate /force exécuté.','t-warn'));return[];});
